// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: ebike_demo

#ifndef _EBIKE_DEMO_UI_H
#define _EBIKE_DEMO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Home.h"
#include "screens/ui_Settings.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * Particle1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Particle2_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Particle3_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Fash_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Wave1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Wave2_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Off_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * On_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Map_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Knob_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_ebike_bg_png);    // assets/ebike_bg.png
LV_IMG_DECLARE(ui_img_speed_slider_png);    // assets/speed_slider.png
LV_IMG_DECLARE(ui_img_slider_battery_png);    // assets/slider_battery.png
LV_IMG_DECLARE(ui_img_icn_flash_png);    // assets/icn_flash.png
LV_IMG_DECLARE(ui_img_menu_on_png);    // assets/menu_on.png
LV_IMG_DECLARE(ui_img_icn_bike_png);    // assets/icn_bike.png
LV_IMG_DECLARE(ui_img_icn_battery_png);    // assets/icn_battery.png
LV_IMG_DECLARE(ui_img_icn_map_png);    // assets/icn_map.png
LV_IMG_DECLARE(ui_img_menu_line_png);    // assets/menu_line.png
LV_IMG_DECLARE(ui_img_particle_1_png);    // assets/particle_1.png
LV_IMG_DECLARE(ui_img_water_2_png);    // assets/water_2.png
LV_IMG_DECLARE(ui_img_particle_3_png);    // assets/particle_3.png
LV_IMG_DECLARE(ui_img_water_1_png);    // assets/water_1.png
LV_IMG_DECLARE(ui_img_particle_2_png);    // assets/particle_2.png
LV_IMG_DECLARE(ui_img_battery_bg_png);    // assets/battery_bg.png
LV_IMG_DECLARE(ui_img_icn_charge_png);    // assets/icn_charge.png
LV_IMG_DECLARE(ui_img_pin_line_png);    // assets/pin_line.png
LV_IMG_DECLARE(ui_img_pin_on_png);    // assets/pin_on.png
LV_IMG_DECLARE(ui_img_icn_x_png);    // assets/icn_x.png
LV_IMG_DECLARE(ui_img_icn_ok_png);    // assets/icn_ok.png
LV_IMG_DECLARE(ui_img_map_png);    // assets/map.png
LV_IMG_DECLARE(ui_img_gps_knob_png);    // assets/gps_knob.png
LV_IMG_DECLARE(ui_img_gps_bg_png);    // assets/gps_bg.png
LV_IMG_DECLARE(ui_img_right_png);    // assets/right.png
LV_IMG_DECLARE(ui_img_settings_corner_png);    // assets/settings_corner.png
LV_IMG_DECLARE(ui_img_icn_settings_png);    // assets/icn_settings.png
LV_IMG_DECLARE(ui_img_settings_bg_png);    // assets/settings_bg.png
LV_IMG_DECLARE(ui_img_volume_on_png);    // assets/volume_on.png
LV_IMG_DECLARE(ui_img_volume_off_png);    // assets/volume_off.png
LV_IMG_DECLARE(ui_img_icn_x2_png);    // assets/icn_x2.png

// FONTS
LV_FONT_DECLARE(ui_font_Big);
LV_FONT_DECLARE(ui_font_Medium);
LV_FONT_DECLARE(ui_font_Number);
LV_FONT_DECLARE(ui_font_Small);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
