// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#ifndef UI_SCREEN_HOME_H
#define UI_SCREEN_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_Home
extern void ui_Screen_Home_screen_init(void);
extern void ui_Screen_Home_screen_destroy(void);
extern void ui_event_Screen_Home(lv_event_t * e);
extern lv_obj_t * ui_Screen_Home;
extern lv_obj_t * ui_Home_header_header4;
extern void ui_event_Home_header_header4_Container_header_panel_Container_right_container_Container_settings(
    lv_event_t * e);
extern lv_obj_t * ui_Home_Container_full_content;
extern lv_obj_t * ui_Home_selector_coffee_selector;
extern void ui_event_Home_selector_coffee_selector_Container_selector__Image_left_chevron(lv_event_t * e);
extern void ui_event_Home_selector_coffee_selector_Container_selector__Image_right_chevron(lv_event_t * e);
extern lv_obj_t * ui_Home_Container_main_parameters;
extern lv_obj_t * ui_Home_Container_content;
extern lv_obj_t * ui_Home_Container_parameters;
extern lv_obj_t * ui_Home_Container_anim_container;
extern lv_obj_t * ui_Home_home_sliders_home_slider;
extern lv_obj_t * ui_Home_Container_anim_container2;
extern lv_obj_t * ui_Home_home_sliders_home_slider1;
extern lv_obj_t * ui_Home_separator_separator;
extern lv_obj_t * ui_Home_CTA_container_CTA_container;
extern void ui_event_Home_CTA_container_CTA_container_Panel_circle_panel(lv_event_t * e);
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

