// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#include "../ui.h"

lv_obj_t * ui_Screen_Home = NULL;
lv_obj_t * ui_Home_header_header4 = NULL;
lv_obj_t * ui_Home_Container_full_content = NULL;
lv_obj_t * ui_Home_selector_coffee_selector = NULL;
lv_obj_t * ui_Home_Container_main_parameters = NULL;
lv_obj_t * ui_Home_Container_content = NULL;
lv_obj_t * ui_Home_Container_parameters = NULL;
lv_obj_t * ui_Home_Container_anim_container = NULL;
lv_obj_t * ui_Home_home_sliders_home_slider = NULL;
lv_obj_t * ui_Home_Container_anim_container2 = NULL;
lv_obj_t * ui_Home_home_sliders_home_slider1 = NULL;
lv_obj_t * ui_Home_separator_separator = NULL;
lv_obj_t * ui_Home_CTA_container_CTA_container = NULL;
// event funtions
void ui_event_Screen_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        left_in_Animation(ui_comp_get_child(ui_Home_selector_coffee_selector, UI_COMP_CONTAINER_SELECTOR_IMAGE_SELECTED_COFFEE),
                          0);
        home_slider_top_Animation(ui_Home_home_sliders_home_slider, 100);
        home_slider_bottom_Animation(ui_Home_home_sliders_home_slider1, 200);
    }
}

void ui_event_Home_header_header4_Container_header_panel_Container_right_container_Container_settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen_Settings_screen_init);
    }
}

void ui_event_Home_selector_coffee_selector_Container_selector__Image_left_chevron(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Home_espresso, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen_Home_espresso_screen_init);
    }
}

void ui_event_Home_selector_coffee_selector_Container_selector__Image_right_chevron(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Home_ristretto, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen_Home_ristretto_screen_init);
    }
}

void ui_event_Home_CTA_container_CTA_container_Panel_circle_panel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Customize, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen_Customize_screen_init);
    }
}

// build funtions

void ui_Screen_Home_screen_init(void)
{
    ui_Screen_Home = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_Home, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Screen_Home, &ui_img_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_header_header4 = ui_Container_header_create(ui_Screen_Home);
    lv_obj_set_x(ui_Home_header_header4, 0);
    lv_obj_set_y(ui_Home_header_header4, 0);

    lv_obj_add_flag(ui_comp_get_child(ui_Home_header_header4,
                                      UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_LEFT_CONTAINER), LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_label_set_text(ui_comp_get_child(ui_Home_header_header4,
                                        UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_LABEL_TITLE), "Choose your coffee");


    ui_Home_Container_full_content = lv_obj_create(ui_Screen_Home);
    lv_obj_remove_style_all(ui_Home_Container_full_content);
    lv_obj_set_height(ui_Home_Container_full_content, 397);
    lv_obj_set_width(ui_Home_Container_full_content, lv_pct(100));
    lv_obj_set_align(ui_Home_Container_full_content, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Home_Container_full_content, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Home_Container_full_content, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Home_Container_full_content, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Home_Container_full_content, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Home_Container_full_content, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Home_Container_full_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Home_Container_full_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Home_Container_full_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Home_Container_full_content, 24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_selector_coffee_selector = ui_Container_selector_create(ui_Home_Container_full_content);
    lv_obj_set_x(ui_Home_selector_coffee_selector, 0);
    lv_obj_set_y(ui_Home_selector_coffee_selector, 0);

    ui_Home_Container_main_parameters = lv_obj_create(ui_Home_Container_full_content);
    lv_obj_remove_style_all(ui_Home_Container_main_parameters);
    lv_obj_set_height(ui_Home_Container_main_parameters, lv_pct(100));
    lv_obj_set_flex_grow(ui_Home_Container_main_parameters, 3);
    lv_obj_set_align(ui_Home_Container_main_parameters, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Home_Container_main_parameters, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Home_Container_main_parameters, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Home_Container_main_parameters, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Home_Container_main_parameters, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Home_Container_main_parameters, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Home_Container_main_parameters, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Home_Container_main_parameters, 44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_Container_content = lv_obj_create(ui_Home_Container_main_parameters);
    lv_obj_remove_style_all(ui_Home_Container_content);
    lv_obj_set_width(ui_Home_Container_content, lv_pct(100));
    lv_obj_set_height(ui_Home_Container_content, lv_pct(100));
    lv_obj_set_align(ui_Home_Container_content, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_Home_Container_content, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Home_Container_content, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Home_Container_content, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Home_Container_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Home_Container_content, 44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_Container_parameters = lv_obj_create(ui_Home_Container_content);
    lv_obj_remove_style_all(ui_Home_Container_parameters);
    lv_obj_set_height(ui_Home_Container_parameters, lv_pct(100));
    lv_obj_set_width(ui_Home_Container_parameters, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_Home_Container_parameters, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Home_Container_parameters, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Home_Container_parameters, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Home_Container_parameters, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Home_Container_anim_container = lv_obj_create(ui_Home_Container_parameters);
    lv_obj_remove_style_all(ui_Home_Container_anim_container);
    lv_obj_set_width(ui_Home_Container_anim_container, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_flex_grow(ui_Home_Container_anim_container, 1);
    lv_obj_set_align(ui_Home_Container_anim_container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Home_Container_anim_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Home_home_sliders_home_slider = ui_Container_home_sliders_create(ui_Home_Container_anim_container);
    lv_obj_set_x(ui_Home_home_sliders_home_slider, 0);
    lv_obj_set_y(ui_Home_home_sliders_home_slider, -2);

    lv_obj_add_flag(ui_comp_get_child(ui_Home_home_sliders_home_slider, UI_COMP_CONTAINER_HOME_SLIDERS_LABEL_LENGTH),
                    LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_obj_remove_flag(ui_comp_get_child(ui_Home_home_sliders_home_slider,
                                         UI_COMP_CONTAINER_HOME_SLIDERS_CONTAINER_STRENGTH_CONTAINER), LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_remove_flag(ui_comp_get_child(ui_Home_home_sliders_home_slider,
                                         UI_COMP_CONTAINER_HOME_SLIDERS_CONTAINER_STRENGTH_CONTAINER_SLIDER_SLIDER_STRENGTH), LV_OBJ_FLAG_HIDDEN);     /// Flags

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    lv_obj_add_flag(ui_comp_get_child(ui_Home_home_sliders_home_slider,
                                      UI_COMP_CONTAINER_HOME_SLIDERS_CONTAINER_LENGTH_CONTAINER), LV_OBJ_FLAG_HIDDEN);    /// Flags

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    ui_Home_Container_anim_container2 = lv_obj_create(ui_Home_Container_parameters);
    lv_obj_remove_style_all(ui_Home_Container_anim_container2);
    lv_obj_set_width(ui_Home_Container_anim_container2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_flex_grow(ui_Home_Container_anim_container2, 1);
    lv_obj_set_align(ui_Home_Container_anim_container2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Home_Container_anim_container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Home_home_sliders_home_slider1 = ui_Container_home_sliders_create(ui_Home_Container_anim_container2);
    lv_obj_set_x(ui_Home_home_sliders_home_slider1, 0);
    lv_obj_set_y(ui_Home_home_sliders_home_slider1, -2);

    lv_obj_remove_flag(ui_comp_get_child(ui_Home_home_sliders_home_slider1, UI_COMP_CONTAINER_HOME_SLIDERS_LABEL_LENGTH),
                       LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_flag(ui_comp_get_child(ui_Home_home_sliders_home_slider1, UI_COMP_CONTAINER_HOME_SLIDERS_LABEL_STRENGTH),
                    LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_obj_add_flag(ui_comp_get_child(ui_Home_home_sliders_home_slider1,
                                      UI_COMP_CONTAINER_HOME_SLIDERS_CONTAINER_STRENGTH_CONTAINER), LV_OBJ_FLAG_HIDDEN);    /// Flags

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    lv_obj_remove_flag(ui_comp_get_child(ui_Home_home_sliders_home_slider1,
                                         UI_COMP_CONTAINER_HOME_SLIDERS_CONTAINER_LENGTH_CONTAINER), LV_OBJ_FLAG_HIDDEN);     /// Flags

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    ui_Home_separator_separator = ui_Container_separator_create(ui_Home_Container_content);
    lv_obj_set_x(ui_Home_separator_separator, 0);
    lv_obj_set_y(ui_Home_separator_separator, 79);

    ui_Home_CTA_container_CTA_container = ui_Container_CTA_container_create(ui_Home_Container_full_content);
    lv_obj_set_x(ui_Home_CTA_container_CTA_container, 0);
    lv_obj_set_y(ui_Home_CTA_container_CTA_container, 0);

    lv_obj_add_event_cb(ui_comp_get_child(ui_Home_header_header4,
                                          UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_SETTINGS),
                        ui_event_Home_header_header4_Container_header_panel_Container_right_container_Container_settings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Home_selector_coffee_selector,
                                          UI_COMP_CONTAINER_SELECTOR_CONTAINER_SELECTOR__IMAGE_LEFT_CHEVRON),
                        ui_event_Home_selector_coffee_selector_Container_selector__Image_left_chevron, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Home_selector_coffee_selector,
                                          UI_COMP_CONTAINER_SELECTOR_CONTAINER_SELECTOR__IMAGE_RIGHT_CHEVRON),
                        ui_event_Home_selector_coffee_selector_Container_selector__Image_right_chevron, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Home_CTA_container_CTA_container,
                                          UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL), ui_event_Home_CTA_container_CTA_container_Panel_circle_panel,
                        LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen_Home, ui_event_Screen_Home, LV_EVENT_ALL, NULL);

}

void ui_Screen_Home_screen_destroy(void)
{
    if(ui_Screen_Home) lv_obj_del(ui_Screen_Home);

    // NULL screen variables
    ui_Screen_Home = NULL;
    ui_Home_header_header4 = NULL;
    ui_Home_Container_full_content = NULL;
    ui_Home_selector_coffee_selector = NULL;
    ui_Home_Container_main_parameters = NULL;
    ui_Home_Container_content = NULL;
    ui_Home_Container_parameters = NULL;
    ui_Home_Container_anim_container = NULL;
    ui_Home_home_sliders_home_slider = NULL;
    ui_Home_Container_anim_container2 = NULL;
    ui_Home_home_sliders_home_slider1 = NULL;
    ui_Home_separator_separator = NULL;
    ui_Home_CTA_container_CTA_container = NULL;

}
