// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#include "../ui.h"

lv_obj_t * ui_Screen_Brewing = NULL;
lv_obj_t * ui_Brewing_header_header5 = NULL;
lv_obj_t * ui_Brewing_Container_full_content = NULL;
lv_obj_t * ui_Brewing_selector_coffee_selector8 = NULL;
lv_obj_t * ui_Brewing_Container_main_parameters = NULL;
lv_obj_t * ui_Brewing_Container_progress_container = NULL;
lv_obj_t * ui_Brewing_Panel_progressbar_bg = NULL;
lv_obj_t * ui_Brewing_Panel_progressbar_fg_ = NULL;
lv_obj_t * ui_Brewing_Container_progress_labels = NULL;
lv_obj_t * ui_Brewing_Label_foam = NULL;
lv_obj_t * ui_Brewing_Label_milk = NULL;
lv_obj_t * ui_Brewing_Label_coffee = NULL;
lv_obj_t * ui_Brewing_Label_wait = NULL;
// event funtions
void ui_event_Screen_Brewing(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        progress_Animation(ui_Brewing_Label_wait, 300);
        progress_Animation(ui_Brewing_Label_coffee, 1800);
        progress_Animation(ui_Brewing_Label_milk, 3300);
        progress_Animation(ui_Brewing_Label_foam, 4800);
        with_Animation(ui_Brewing_Panel_progressbar_fg_, 0);
        with_progress_Animation(ui_Brewing_Container_main_parameters, 0);
        latte_close_Animation(ui_Brewing_selector_coffee_selector8, 0);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_Screen_Brewing_Done, LV_SCR_LOAD_ANIM_FADE_ON, 0, 6200, &ui_Screen_Brewing_Done_screen_init);
    }
}

// build funtions

void ui_Screen_Brewing_screen_init(void)
{
    ui_Screen_Brewing = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_Brewing, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_Brewing, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_Brewing, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Screen_Brewing, &ui_img_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Brewing_header_header5 = ui_Container_header_create(ui_Screen_Brewing);
    lv_obj_set_x(ui_Brewing_header_header5, 0);
    lv_obj_set_y(ui_Brewing_header_header5, 0);

    lv_obj_add_state(ui_comp_get_child(ui_Brewing_header_header5,
                                       UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_LEFT_CONTAINER_CONTAINER_BACK_BTN),
                     LV_STATE_DISABLED);      /// States
    lv_obj_remove_flag(ui_comp_get_child(ui_Brewing_header_header5,
                                         UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_LEFT_CONTAINER_CONTAINER_BACK_BTN),
                       LV_OBJ_FLAG_CLICKABLE);    /// Flags

    lv_label_set_text(ui_comp_get_child(ui_Brewing_header_header5,
                                        UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_LABEL_TITLE), "Brewing");

    lv_obj_remove_flag(ui_comp_get_child(ui_Brewing_header_header5,
                                         UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_STATUS_ICONS_CONTAINER_ICONS_ROW_IMAGE_WIFI),
                       LV_OBJ_FLAG_CLICKABLE);     /// Flags

    lv_obj_add_state(ui_comp_get_child(ui_Brewing_header_header5,
                                       UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_SETTINGS),
                     LV_STATE_DISABLED);      /// States
    lv_obj_remove_flag(ui_comp_get_child(ui_Brewing_header_header5,
                                         UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_SETTINGS),
                       LV_OBJ_FLAG_CLICKABLE);    /// Flags

    ui_Brewing_Container_full_content = lv_obj_create(ui_Screen_Brewing);
    lv_obj_remove_style_all(ui_Brewing_Container_full_content);
    lv_obj_set_height(ui_Brewing_Container_full_content, 397);
    lv_obj_set_width(ui_Brewing_Container_full_content, lv_pct(100));
    lv_obj_set_align(ui_Brewing_Container_full_content, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_Brewing_Container_full_content, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Brewing_Container_full_content, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Brewing_Container_full_content, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Brewing_Container_full_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Brewing_Container_full_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Brewing_Container_full_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Brewing_Container_full_content, 48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Brewing_selector_coffee_selector8 = ui_Container_selector_create(ui_Brewing_Container_full_content);
    lv_obj_set_width(ui_Brewing_selector_coffee_selector8, 264);
    lv_obj_set_height(ui_Brewing_selector_coffee_selector8, lv_pct(100));
    lv_obj_set_flex_grow(ui_Brewing_selector_coffee_selector8, 0);
    lv_obj_set_x(ui_Brewing_selector_coffee_selector8, 0);
    lv_obj_set_y(ui_Brewing_selector_coffee_selector8, 0);

    lv_obj_add_flag(ui_comp_get_child(ui_Brewing_selector_coffee_selector8,
                                      UI_COMP_CONTAINER_SELECTOR_CONTAINER_SELECTOR__IMAGE_LEFT_CHEVRON), LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_obj_add_flag(ui_comp_get_child(ui_Brewing_selector_coffee_selector8,
                                      UI_COMP_CONTAINER_SELECTOR_CONTAINER_SELECTOR__IMAGE_RIGHT_CHEVRON), LV_OBJ_FLAG_HIDDEN);    /// Flags

    ui_Brewing_Container_main_parameters = lv_obj_create(ui_Brewing_Container_full_content);
    lv_obj_remove_style_all(ui_Brewing_Container_main_parameters);
    lv_obj_set_width(ui_Brewing_Container_main_parameters, 440);
    lv_obj_set_height(ui_Brewing_Container_main_parameters, lv_pct(100));
    lv_obj_set_align(ui_Brewing_Container_main_parameters, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_Brewing_Container_main_parameters, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Brewing_Container_main_parameters, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Brewing_Container_main_parameters, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Brewing_Container_main_parameters, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Brewing_Container_main_parameters, 44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Brewing_Container_progress_container = lv_obj_create(ui_Brewing_Container_main_parameters);
    lv_obj_remove_style_all(ui_Brewing_Container_progress_container);
    lv_obj_set_width(ui_Brewing_Container_progress_container, 440);
    lv_obj_set_height(ui_Brewing_Container_progress_container, lv_pct(100));
    lv_obj_set_align(ui_Brewing_Container_progress_container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Brewing_Container_progress_container,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Brewing_Container_progress_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Brewing_Container_progress_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Brewing_Container_progress_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Brewing_Container_progress_container, 48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Brewing_Container_progress_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Brewing_Container_progress_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Brewing_Panel_progressbar_bg = lv_obj_create(ui_Brewing_Container_progress_container);
    lv_obj_set_width(ui_Brewing_Panel_progressbar_bg, 267);
    lv_obj_set_height(ui_Brewing_Panel_progressbar_bg, 16);
    lv_obj_set_x(ui_Brewing_Panel_progressbar_bg, 0);
    lv_obj_set_y(ui_Brewing_Panel_progressbar_bg, 30);
    lv_obj_set_align(ui_Brewing_Panel_progressbar_bg, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Brewing_Panel_progressbar_bg, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Brewing_Panel_progressbar_bg, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Brewing_Panel_progressbar_bg, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_fg_Secondary);
    ui_object_set_themeable_style_property(ui_Brewing_Panel_progressbar_bg, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_fg_Secondary);
    lv_obj_set_style_clip_corner(ui_Brewing_Panel_progressbar_bg, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Brewing_Panel_progressbar_bg, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_OUTLINE_COLOR, _ui_theme_color_border_Secondary);
    ui_object_set_themeable_style_property(ui_Brewing_Panel_progressbar_bg, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_OUTLINE_OPA, _ui_theme_alpha_border_Secondary);
    lv_obj_set_style_outline_width(ui_Brewing_Panel_progressbar_bg, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Brewing_Panel_progressbar_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Brewing_Panel_progressbar_bg, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_SHADOW_COLOR, _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(ui_Brewing_Panel_progressbar_bg, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_SHADOW_OPA, _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_shadow_width(ui_Brewing_Panel_progressbar_bg, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Brewing_Panel_progressbar_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Brewing_Panel_progressbar_fg_ = lv_obj_create(ui_Brewing_Panel_progressbar_bg);
    lv_obj_set_width(ui_Brewing_Panel_progressbar_fg_, 0);
    lv_obj_set_height(ui_Brewing_Panel_progressbar_fg_, 50);
    lv_obj_set_align(ui_Brewing_Panel_progressbar_fg_, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_Brewing_Panel_progressbar_fg_, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Brewing_Panel_progressbar_fg_, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Brewing_Panel_progressbar_fg_, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(ui_Brewing_Panel_progressbar_fg_, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_fg_Primary);

    ui_Brewing_Container_progress_labels = lv_obj_create(ui_Brewing_Container_progress_container);
    lv_obj_remove_style_all(ui_Brewing_Container_progress_labels);
    lv_obj_set_width(ui_Brewing_Container_progress_labels, 267);
    lv_obj_set_height(ui_Brewing_Container_progress_labels, 87);
    lv_obj_set_align(ui_Brewing_Container_progress_labels, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Brewing_Container_progress_labels, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Brewing_Container_progress_labels, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Brewing_Container_progress_labels, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Brewing_Container_progress_labels, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Brewing_Container_progress_labels, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Brewing_Container_progress_labels, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Brewing_Container_progress_labels, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Brewing_Label_foam = lv_label_create(ui_Brewing_Container_progress_labels);
    lv_obj_set_width(ui_Brewing_Label_foam, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Brewing_Label_foam, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Brewing_Label_foam, 0);
    lv_obj_set_y(ui_Brewing_Label_foam, -24);
    lv_obj_set_align(ui_Brewing_Label_foam, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Brewing_Label_foam, "Foam");
    ui_object_set_themeable_style_property(ui_Brewing_Label_foam, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(ui_Brewing_Label_foam, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_text_font(ui_Brewing_Label_foam, &ui_font_H3_bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Brewing_Label_foam, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Brewing_Label_milk = lv_label_create(ui_Brewing_Container_progress_labels);
    lv_obj_set_width(ui_Brewing_Label_milk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Brewing_Label_milk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Brewing_Label_milk, 0);
    lv_obj_set_y(ui_Brewing_Label_milk, -24);
    lv_obj_set_align(ui_Brewing_Label_milk, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Brewing_Label_milk, "Milk");
    ui_object_set_themeable_style_property(ui_Brewing_Label_milk, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(ui_Brewing_Label_milk, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_text_font(ui_Brewing_Label_milk, &ui_font_H3_bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Brewing_Label_milk, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Brewing_Label_coffee = lv_label_create(ui_Brewing_Container_progress_labels);
    lv_obj_set_width(ui_Brewing_Label_coffee, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Brewing_Label_coffee, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Brewing_Label_coffee, 0);
    lv_obj_set_y(ui_Brewing_Label_coffee, -24);
    lv_obj_set_align(ui_Brewing_Label_coffee, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Brewing_Label_coffee, "Coffee");
    ui_object_set_themeable_style_property(ui_Brewing_Label_coffee, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(ui_Brewing_Label_coffee, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_text_font(ui_Brewing_Label_coffee, &ui_font_H3_bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Brewing_Label_coffee, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Brewing_Label_wait = lv_label_create(ui_Brewing_Container_progress_labels);
    lv_obj_set_width(ui_Brewing_Label_wait, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Brewing_Label_wait, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Brewing_Label_wait, 0);
    lv_obj_set_y(ui_Brewing_Label_wait, -24);
    lv_obj_set_align(ui_Brewing_Label_wait, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Brewing_Label_wait, "Please wait...");
    ui_object_set_themeable_style_property(ui_Brewing_Label_wait, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(ui_Brewing_Label_wait, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_text_font(ui_Brewing_Label_wait, &ui_font_H3_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen_Brewing, ui_event_Screen_Brewing, LV_EVENT_ALL, NULL);

}

void ui_Screen_Brewing_screen_destroy(void)
{
    if(ui_Screen_Brewing) lv_obj_del(ui_Screen_Brewing);

    // NULL screen variables
    ui_Screen_Brewing = NULL;
    ui_Brewing_header_header5 = NULL;
    ui_Brewing_Container_full_content = NULL;
    ui_Brewing_selector_coffee_selector8 = NULL;
    ui_Brewing_Container_main_parameters = NULL;
    ui_Brewing_Container_progress_container = NULL;
    ui_Brewing_Panel_progressbar_bg = NULL;
    ui_Brewing_Panel_progressbar_fg_ = NULL;
    ui_Brewing_Container_progress_labels = NULL;
    ui_Brewing_Label_foam = NULL;
    ui_Brewing_Label_milk = NULL;
    ui_Brewing_Label_coffee = NULL;
    ui_Brewing_Label_wait = NULL;

}
