// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#include "../ui.h"

lv_obj_t * ui_Screen_Add_water = NULL;
lv_obj_t * ui_Add_water_header_header9 = NULL;
lv_obj_t * ui_Add_water_Container_middle_content = NULL;
lv_obj_t * ui_Add_water_Container_exclamation_container = NULL;
lv_obj_t * ui_Add_water_CTA_container_CTA_container8 = NULL;
lv_obj_t * ui_Add_water_Container_mid_container = NULL;
lv_obj_t * ui_Add_water_Image_tank = NULL;
lv_obj_t * ui_Add_water_Container_waves_ = NULL;
lv_obj_t * ui_Add_water_Image_wave_bg = NULL;
lv_obj_t * ui_Add_water_Image_wave_fg = NULL;
lv_obj_t * ui_Add_water_Image_wave_bottom = NULL;
lv_obj_t * ui_Add_water_Label_min = NULL;
lv_obj_t * ui_Add_water_Container_Done_container = NULL;
lv_obj_t * ui_Add_water_CTA_container_CTA_container6 = NULL;
lv_obj_t * ui_Add_water_Container_footer = NULL;
lv_obj_t * ui_Add_water_Label_refill = NULL;
// event funtions
void ui_event_Screen_Add_water(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        vector_top_on_Animation(ui_Add_water_Image_tank, 0);
        refill_bottom_on_Animation(ui_Add_water_Label_refill, 100);
        min_top_on_Animation(ui_Add_water_Label_min, 0);
        wave_loop_fg_Animation(ui_Add_water_Image_wave_fg, 0);
        wave_loop_bg_Animation(ui_Add_water_Image_wave_bg, 0);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        vector_top_off_Animation(ui_Add_water_Image_tank, 0);
        refill_bottom_off_Animation(ui_Add_water_Label_refill, 0);
        min_top_off_Animation(ui_Add_water_Label_min, 0);
    }
}

void ui_event_Add_water_CTA_container_CTA_container6_Panel_circle_panel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Add_coffee, LV_SCR_LOAD_ANIM_FADE_ON, 0, 300, &ui_Screen_Add_coffee_screen_init);
    }
}

// build funtions

void ui_Screen_Add_water_screen_init(void)
{
    ui_Screen_Add_water = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_Add_water, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Screen_Add_water, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Screen_Add_water, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_Screen_Add_water, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_Add_water, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Screen_Add_water, &ui_img_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Add_water_header_header9 = ui_Container_header_create(ui_Screen_Add_water);
    lv_obj_set_x(ui_Add_water_header_header9, 0);
    lv_obj_set_y(ui_Add_water_header_header9, 0);

    lv_obj_add_state(ui_comp_get_child(ui_Add_water_header_header9,
                                       UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_LEFT_CONTAINER_CONTAINER_BACK_BTN),
                     LV_STATE_DISABLED);      /// States
    lv_obj_remove_flag(ui_comp_get_child(ui_Add_water_header_header9,
                                         UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_LEFT_CONTAINER_CONTAINER_BACK_BTN),
                       LV_OBJ_FLAG_CLICKABLE);    /// Flags
    lv_obj_set_style_bg_image_opa(ui_comp_get_child(ui_Add_water_header_header9,
                                                    UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_LEFT_CONTAINER_CONTAINER_BACK_BTN), 85,
                                  LV_PART_MAIN | LV_STATE_DISABLED);
    ui_object_set_themeable_style_property(ui_comp_get_child(ui_Add_water_header_header9,
                                                             UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_LEFT_CONTAINER_CONTAINER_BACK_BTN),
                                           LV_PART_MAIN | LV_STATE_DISABLED, LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_fg_Disabled);
    ui_object_set_themeable_style_property(ui_comp_get_child(ui_Add_water_header_header9,
                                                             UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_LEFT_CONTAINER_CONTAINER_BACK_BTN),
                                           LV_PART_MAIN | LV_STATE_DISABLED, LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_fg_Disabled);

    lv_label_set_text(ui_comp_get_child(ui_Add_water_header_header9,
                                        UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_LABEL_TITLE), "Add water");

    lv_obj_remove_flag(ui_comp_get_child(ui_Add_water_header_header9,
                                         UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_STATUS_ICONS_CONTAINER_ICONS_ROW_IMAGE_WIFI),
                       LV_OBJ_FLAG_CLICKABLE);     /// Flags

    lv_obj_add_state(ui_comp_get_child(ui_Add_water_header_header9,
                                       UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_SETTINGS),
                     LV_STATE_DISABLED);      /// States
    lv_obj_remove_flag(ui_comp_get_child(ui_Add_water_header_header9,
                                         UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_SETTINGS),
                       LV_OBJ_FLAG_CLICKABLE);    /// Flags
    lv_obj_set_style_bg_image_opa(ui_comp_get_child(ui_Add_water_header_header9,
                                                    UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_SETTINGS), 85,
                                  LV_PART_MAIN | LV_STATE_DISABLED);

    ui_Add_water_Container_middle_content = lv_obj_create(ui_Screen_Add_water);
    lv_obj_remove_style_all(ui_Add_water_Container_middle_content);
    lv_obj_set_width(ui_Add_water_Container_middle_content, lv_pct(100));
    lv_obj_set_flex_grow(ui_Add_water_Container_middle_content, 1);
    lv_obj_set_align(ui_Add_water_Container_middle_content, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Add_water_Container_middle_content, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Add_water_Container_middle_content, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Add_water_Container_middle_content,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Add_water_Container_middle_content, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Add_water_Container_middle_content, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Add_water_Container_middle_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Add_water_Container_middle_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Add_water_Container_middle_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Add_water_Container_middle_content, 24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Add_water_Container_exclamation_container = lv_obj_create(ui_Add_water_Container_middle_content);
    lv_obj_remove_style_all(ui_Add_water_Container_exclamation_container);
    lv_obj_set_height(ui_Add_water_Container_exclamation_container, lv_pct(100));
    lv_obj_set_flex_grow(ui_Add_water_Container_exclamation_container, 3);
    lv_obj_set_align(ui_Add_water_Container_exclamation_container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Add_water_Container_exclamation_container,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Add_water_CTA_container_CTA_container8 = ui_Container_CTA_container_create(
                                                    ui_Add_water_Container_exclamation_container);
    lv_obj_set_width(ui_Add_water_CTA_container_CTA_container8, lv_pct(100));
    lv_obj_set_height(ui_Add_water_CTA_container_CTA_container8, lv_pct(100));
    lv_obj_set_flex_grow(ui_Add_water_CTA_container_CTA_container8, 0);
    lv_obj_set_x(ui_Add_water_CTA_container_CTA_container8, 0);
    lv_obj_set_y(ui_Add_water_CTA_container_CTA_container8, 6);
    lv_obj_set_flex_flow(ui_Add_water_CTA_container_CTA_container8, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Add_water_CTA_container_CTA_container8, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_left(ui_Add_water_CTA_container_CTA_container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Add_water_CTA_container_CTA_container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Add_water_CTA_container_CTA_container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Add_water_CTA_container_CTA_container8, 44, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_state(ui_comp_get_child(ui_Add_water_CTA_container_CTA_container8,
                                       UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL), LV_STATE_PRESSED);      /// States
    lv_obj_remove_flag(ui_comp_get_child(ui_Add_water_CTA_container_CTA_container8,
                                         UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL), LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_bg_image_opa(ui_comp_get_child(ui_Add_water_CTA_container_CTA_container8,
                                                    UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL), 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_comp_get_child(ui_Add_water_CTA_container_CTA_container8,
                                                    UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL), 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_comp_get_child(ui_Add_water_CTA_container_CTA_container8,
                                                    UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL), lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_comp_get_child(ui_Add_water_CTA_container_CTA_container8,
                                                  UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL), 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_comp_get_child(ui_Add_water_CTA_container_CTA_container8,
                                                    UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL), 4, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_remove_flag(ui_comp_get_child(ui_Add_water_CTA_container_CTA_container8,
                                         UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL_LABEL_EXCLAMATION), LV_OBJ_FLAG_HIDDEN);     /// Flags
    ui_object_set_themeable_style_property(ui_comp_get_child(ui_Add_water_CTA_container_CTA_container8,
                                                             UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL_LABEL_EXCLAMATION), LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(ui_comp_get_child(ui_Add_water_CTA_container_CTA_container8,
                                                             UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL_LABEL_EXCLAMATION), LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_fg_Primary);

    lv_obj_add_flag(ui_comp_get_child(ui_Add_water_CTA_container_CTA_container8,
                                      UI_COMP_CONTAINER_CTA_CONTAINER_LABEL_EXTRACT), LV_OBJ_FLAG_HIDDEN);    /// Flags

    ui_Add_water_Container_mid_container = lv_obj_create(ui_Add_water_Container_middle_content);
    lv_obj_remove_style_all(ui_Add_water_Container_mid_container);
    lv_obj_set_width(ui_Add_water_Container_mid_container, 205);
    lv_obj_set_height(ui_Add_water_Container_mid_container, lv_pct(100));
    lv_obj_set_align(ui_Add_water_Container_mid_container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Add_water_Container_mid_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Add_water_Image_tank = lv_image_create(ui_Add_water_Container_mid_container);
    lv_image_set_src(ui_Add_water_Image_tank, &ui_img_tank_png);
    lv_obj_set_width(ui_Add_water_Image_tank, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Add_water_Image_tank, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Add_water_Image_tank, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Add_water_Image_tank, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Add_water_Image_tank, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Add_water_Container_waves_ = lv_obj_create(ui_Add_water_Image_tank);
    lv_obj_remove_style_all(ui_Add_water_Container_waves_);
    lv_obj_set_width(ui_Add_water_Container_waves_, 131);
    lv_obj_set_height(ui_Add_water_Container_waves_, 55);
    lv_obj_set_x(ui_Add_water_Container_waves_, 0);
    lv_obj_set_y(ui_Add_water_Container_waves_, 55);
    lv_obj_set_align(ui_Add_water_Container_waves_, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Add_water_Container_waves_, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Add_water_Image_wave_bg = lv_image_create(ui_Add_water_Container_waves_);
    lv_image_set_src(ui_Add_water_Image_wave_bg, &ui_img_wave1_png);
    lv_obj_set_width(ui_Add_water_Image_wave_bg, 798);
    lv_obj_set_height(ui_Add_water_Image_wave_bg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Add_water_Image_wave_bg, -65);
    lv_obj_set_y(ui_Add_water_Image_wave_bg, -19);
    lv_obj_set_align(ui_Add_water_Image_wave_bg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Add_water_Image_wave_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Add_water_Image_wave_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_Add_water_Image_wave_bg, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_image_recolor(ui_Add_water_Image_wave_bg, lv_color_hex(0x5E6469), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_Add_water_Image_wave_bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Add_water_Image_wave_fg = lv_image_create(ui_Add_water_Container_waves_);
    lv_image_set_src(ui_Add_water_Image_wave_fg, &ui_img_wave1_png);
    lv_obj_set_width(ui_Add_water_Image_wave_fg, 798);
    lv_obj_set_height(ui_Add_water_Image_wave_fg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Add_water_Image_wave_fg, 1);
    lv_obj_set_y(ui_Add_water_Image_wave_fg, -19);
    lv_obj_set_align(ui_Add_water_Image_wave_fg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Add_water_Image_wave_fg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Add_water_Image_wave_fg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_Add_water_Image_wave_fg, LV_IMAGE_ALIGN_TILE);

    ui_Add_water_Image_wave_bottom = lv_image_create(ui_Add_water_Container_waves_);
    lv_image_set_src(ui_Add_water_Image_wave_bottom, &ui_img_wave_bottom_png);
    lv_obj_set_width(ui_Add_water_Image_wave_bottom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Add_water_Image_wave_bottom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Add_water_Image_wave_bottom, 1);
    lv_obj_set_y(ui_Add_water_Image_wave_bottom, 8);
    lv_obj_set_align(ui_Add_water_Image_wave_bottom, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Add_water_Image_wave_bottom, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Add_water_Image_wave_bottom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Add_water_Label_min = lv_label_create(ui_Add_water_Container_mid_container);
    lv_obj_set_width(ui_Add_water_Label_min, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Add_water_Label_min, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Add_water_Label_min, 92);
    lv_obj_set_y(ui_Add_water_Label_min, -1);
    lv_obj_set_align(ui_Add_water_Label_min, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Add_water_Label_min, "Min");
    ui_object_set_themeable_style_property(ui_Add_water_Label_min, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(ui_Add_water_Label_min, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_text_font(ui_Add_water_Label_min, &ui_font_icon, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Add_water_Container_Done_container = lv_obj_create(ui_Add_water_Container_middle_content);
    lv_obj_remove_style_all(ui_Add_water_Container_Done_container);
    lv_obj_set_height(ui_Add_water_Container_Done_container, lv_pct(100));
    lv_obj_set_flex_grow(ui_Add_water_Container_Done_container, 3);
    lv_obj_set_align(ui_Add_water_Container_Done_container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Add_water_Container_Done_container,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Add_water_CTA_container_CTA_container6 = ui_Container_CTA_container_create(ui_Add_water_Container_Done_container);
    lv_obj_set_width(ui_Add_water_CTA_container_CTA_container6, lv_pct(100));
    lv_obj_set_height(ui_Add_water_CTA_container_CTA_container6, lv_pct(100));
    lv_obj_set_flex_grow(ui_Add_water_CTA_container_CTA_container6, 0);
    lv_obj_set_x(ui_Add_water_CTA_container_CTA_container6, 0);
    lv_obj_set_y(ui_Add_water_CTA_container_CTA_container6, 24);
    lv_obj_set_flex_flow(ui_Add_water_CTA_container_CTA_container6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Add_water_CTA_container_CTA_container6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);

    lv_obj_add_flag(ui_comp_get_child(ui_Add_water_CTA_container_CTA_container6,
                                      UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL), LV_OBJ_FLAG_CLICKABLE);    /// Flags
    lv_obj_set_style_bg_image_src(ui_comp_get_child(ui_Add_water_CTA_container_CTA_container6,
                                                    UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL), &ui_img_done_60_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_comp_get_child(ui_Add_water_CTA_container_CTA_container6,
                                                    UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL), 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_comp_get_child(ui_Add_water_CTA_container_CTA_container6,
                                                    UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL), 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_comp_get_child(ui_Add_water_CTA_container_CTA_container6,
                                                    UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL), &ui_img_done_60_png, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_flag(ui_comp_get_child(ui_Add_water_CTA_container_CTA_container6,
                                      UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL_LABEL_EXCLAMATION), LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_label_set_text(ui_comp_get_child(ui_Add_water_CTA_container_CTA_container6,
                                        UI_COMP_CONTAINER_CTA_CONTAINER_LABEL_EXTRACT), "Ready");
    lv_obj_remove_flag(ui_comp_get_child(ui_Add_water_CTA_container_CTA_container6,
                                         UI_COMP_CONTAINER_CTA_CONTAINER_LABEL_EXTRACT), LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Add_water_Container_footer = lv_obj_create(ui_Screen_Add_water);
    lv_obj_remove_style_all(ui_Add_water_Container_footer);
    lv_obj_set_height(ui_Add_water_Container_footer, 81);
    lv_obj_set_width(ui_Add_water_Container_footer, lv_pct(100));
    lv_obj_set_align(ui_Add_water_Container_footer, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_Add_water_Container_footer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Add_water_Label_refill = lv_label_create(ui_Add_water_Container_footer);
    lv_obj_set_width(ui_Add_water_Label_refill, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Add_water_Label_refill, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Add_water_Label_refill, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Add_water_Label_refill, "Fill water to the minimum sign for further coffee brewing");
    ui_object_set_themeable_style_property(ui_Add_water_Label_refill, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(ui_Add_water_Label_refill, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_text_font(ui_Add_water_Label_refill, &ui_font_P2_medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_comp_get_child(ui_Add_water_CTA_container_CTA_container6,
                                          UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL), ui_event_Add_water_CTA_container_CTA_container6_Panel_circle_panel,
                        LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen_Add_water, ui_event_Screen_Add_water, LV_EVENT_ALL, NULL);

}

void ui_Screen_Add_water_screen_destroy(void)
{
    if(ui_Screen_Add_water) lv_obj_del(ui_Screen_Add_water);

    // NULL screen variables
    ui_Screen_Add_water = NULL;
    ui_Add_water_header_header9 = NULL;
    ui_Add_water_Container_middle_content = NULL;
    ui_Add_water_Container_exclamation_container = NULL;
    ui_Add_water_CTA_container_CTA_container8 = NULL;
    ui_Add_water_Container_mid_container = NULL;
    ui_Add_water_Image_tank = NULL;
    ui_Add_water_Container_waves_ = NULL;
    ui_Add_water_Image_wave_bg = NULL;
    ui_Add_water_Image_wave_fg = NULL;
    ui_Add_water_Image_wave_bottom = NULL;
    ui_Add_water_Label_min = NULL;
    ui_Add_water_Container_Done_container = NULL;
    ui_Add_water_CTA_container_CTA_container6 = NULL;
    ui_Add_water_Container_footer = NULL;
    ui_Add_water_Label_refill = NULL;

}
