// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#include "../ui.h"

// COMPONENT parameter

lv_obj_t * ui_Container_parameter_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Container_parameter;
    cui_Container_parameter = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Container_parameter);
    lv_obj_set_height(cui_Container_parameter, lv_pct(100));
    lv_obj_set_width(cui_Container_parameter, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(cui_Container_parameter, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Container_parameter, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(cui_Container_parameter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Container_parameter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Container_parameter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Container_parameter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_Container_parameter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Container_parameter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Container_slider;
    cui_Container_slider = lv_obj_create(cui_Container_parameter);
    lv_obj_remove_style_all(cui_Container_slider);
    lv_obj_set_width(cui_Container_slider, 48);
    lv_obj_set_height(cui_Container_slider, 182);
    lv_obj_set_align(cui_Container_slider, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(cui_Container_slider, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(cui_Container_slider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Container_slider, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Container_slider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Container_slider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Slider_slider_body;
    cui_Slider_slider_body = lv_slider_create(cui_Container_slider);
    lv_slider_set_range(cui_Slider_slider_body, 0, 80);
    lv_slider_set_value(cui_Slider_slider_body, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(cui_Slider_slider_body) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(cui_Slider_slider_body,
                                                                                                        0, LV_ANIM_OFF);
    lv_obj_set_width(cui_Slider_slider_body, 24);
    lv_obj_set_height(cui_Slider_slider_body, 176);
    lv_obj_set_align(cui_Slider_slider_body, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(cui_Slider_slider_body, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Slider_slider_body, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(cui_Slider_slider_body, &ui_img_slider_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(cui_Slider_slider_body, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Slider_slider_body, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fg_Disabled);
    ui_object_set_themeable_style_property(cui_Slider_slider_body, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fg_Disabled);

    lv_obj_set_style_bg_color(cui_Slider_slider_body, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Slider_slider_body, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(cui_Slider_slider_body, &ui_img_top_png, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(cui_Slider_slider_body,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(cui_Slider_slider_body, lv_obj_get_style_pad_right(cui_Slider_slider_body,
                                                                                  LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_t * cui_Image_slider_icon;
    cui_Image_slider_icon = lv_image_create(cui_Container_parameter);
    lv_image_set_src(cui_Image_slider_icon, &ui_img_parameters_png);
    lv_obj_set_width(cui_Image_slider_icon, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(cui_Image_slider_icon, LV_SIZE_CONTENT);    /// 49
    lv_obj_set_x(cui_Image_slider_icon, 0);
    lv_obj_set_y(cui_Image_slider_icon, -4);
    lv_obj_set_align(cui_Image_slider_icon, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(cui_Image_slider_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(cui_Image_slider_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINER_PARAMETER_NUM);
    children[UI_COMP_CONTAINER_PARAMETER_CONTAINER_PARAMETER] = cui_Container_parameter;
    children[UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER] = cui_Container_slider;
    children[UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY] = cui_Slider_slider_body;
    children[UI_COMP_CONTAINER_PARAMETER_IMAGE_SLIDER_ICON] = cui_Image_slider_icon;
    lv_obj_add_event_cb(cui_Container_parameter, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Container_parameter, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Container_parameter_create_hook(cui_Container_parameter);
    return cui_Container_parameter;
}

