// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#include "../ui.h"

// COMPONENT homeslider

lv_obj_t * ui_Container_homeslider_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Container_homeslider;
    cui_Container_homeslider = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Container_homeslider);
    lv_obj_set_width(cui_Container_homeslider, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_flex_grow(cui_Container_homeslider, 1);
    lv_obj_set_align(cui_Container_homeslider, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Container_homeslider, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_Container_homeslider, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_Container_homeslider, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(cui_Container_homeslider, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Container_homeslider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label_cs_label1;
    cui_Label_cs_label1 = lv_label_create(cui_Container_homeslider);
    lv_obj_set_width(cui_Label_cs_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label_cs_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label_cs_label1, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label_cs_label1, "Coffee Strength");
    ui_object_set_themeable_style_property(cui_Label_cs_label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Label_cs_label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_text_font(cui_Label_cs_label1, &ui_font_P1_medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Slider_Slider4;
    cui_Slider_Slider4 = lv_slider_create(cui_Container_homeslider);
    lv_slider_set_range(cui_Slider_Slider4, 0, 4);
    lv_slider_set_value(cui_Slider_Slider4, 2, LV_ANIM_OFF);
    if(lv_slider_get_mode(cui_Slider_Slider4) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(cui_Slider_Slider4, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(cui_Slider_Slider4, 219);
    lv_obj_set_height(cui_Slider_Slider4, 48);
    lv_obj_set_align(cui_Slider_Slider4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Slider_Slider4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Slider_Slider4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(cui_Slider_Slider4, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Slider_Slider4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_Slider_Slider4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Slider_Slider4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(cui_Slider_Slider4, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(cui_Slider_Slider4,
                                                                                                      lv_obj_get_style_pad_right(cui_Slider_Slider4, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINER_HOMESLIDER_NUM);
    children[UI_COMP_CONTAINER_HOMESLIDER_CONTAINER_HOMESLIDER] = cui_Container_homeslider;
    children[UI_COMP_CONTAINER_HOMESLIDER_LABEL_CS_LABEL1] = cui_Label_cs_label1;
    children[UI_COMP_CONTAINER_HOMESLIDER_SLIDER_SLIDER4] = cui_Slider_Slider4;
    lv_obj_add_event_cb(cui_Container_homeslider, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Container_homeslider, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Container_homeslider_create_hook(cui_Container_homeslider);
    return cui_Container_homeslider;
}

