// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#ifndef _UI_COMP_SLIDER1_H
#define _UI_COMP_SLIDER1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Slider1
#define UI_COMP_SLIDER_SLIDER1_SLIDER_SLIDER1 0
#define _UI_COMP_SLIDER_SLIDER1_NUM 1
lv_obj_t * ui_Slider_Slider1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
