// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#include "../ui.h"

// COMPONENT selector

lv_obj_t * ui_Container_selector_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Container_selector;
    cui_Container_selector = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Container_selector);
    lv_obj_set_height(cui_Container_selector, lv_pct(100));
    lv_obj_set_flex_grow(cui_Container_selector, 3);
    lv_obj_set_align(cui_Container_selector, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(cui_Container_selector, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Image_selected_coffee;
    cui_Image_selected_coffee = lv_image_create(cui_Container_selector);
    lv_image_set_src(cui_Image_selected_coffee, &ui_img_latte_illustration_png);
    lv_obj_set_width(cui_Image_selected_coffee, LV_SIZE_CONTENT);   /// 265
    lv_obj_set_height(cui_Image_selected_coffee, LV_SIZE_CONTENT);    /// 501
    lv_obj_set_x(cui_Image_selected_coffee, 0);
    lv_obj_set_y(cui_Image_selected_coffee, 24);
    lv_obj_set_align(cui_Image_selected_coffee, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(cui_Image_selected_coffee, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(cui_Image_selected_coffee, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Container_selector_;
    cui_Container_selector_ = lv_obj_create(cui_Container_selector);
    lv_obj_remove_style_all(cui_Container_selector_);
    lv_obj_set_height(cui_Container_selector_, 50);
    lv_obj_set_width(cui_Container_selector_, lv_pct(100));
    lv_obj_set_x(cui_Container_selector_, 0);
    lv_obj_set_y(cui_Container_selector_, -45);
    lv_obj_set_align(cui_Container_selector_, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(cui_Container_selector_, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Container_selector_, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Container_selector_, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Image_left_chevron;
    cui_Image_left_chevron = lv_image_create(cui_Container_selector_);
    lv_image_set_src(cui_Image_left_chevron, &ui_img_chevron_png);
    lv_obj_set_width(cui_Image_left_chevron, 48);
    lv_obj_set_height(cui_Image_left_chevron, 48);
    lv_obj_set_align(cui_Image_left_chevron, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image_left_chevron, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(cui_Image_left_chevron, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(cui_Image_left_chevron, LV_IMAGE_ALIGN_TILE);
    ui_object_set_themeable_style_property(cui_Image_left_chevron, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Image_left_chevron, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_fg_Primary);

    lv_obj_t * cui_Container_coffee_name;
    cui_Container_coffee_name = lv_obj_create(cui_Container_selector_);
    lv_obj_remove_style_all(cui_Container_coffee_name);
    lv_obj_set_width(cui_Container_coffee_name, 127);
    lv_obj_set_height(cui_Container_coffee_name, 52);
    lv_obj_set_align(cui_Container_coffee_name, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Container_coffee_name, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_Container_coffee_name, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Container_coffee_name, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label_coffee_prefix;
    cui_Label_coffee_prefix = lv_label_create(cui_Container_coffee_name);
    lv_obj_set_width(cui_Label_coffee_prefix, LV_SIZE_CONTENT);   /// 126
    lv_obj_set_height(cui_Label_coffee_prefix, LV_SIZE_CONTENT);    /// 52
    lv_obj_set_align(cui_Label_coffee_prefix, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label_coffee_prefix, "Latte");
    ui_object_set_themeable_style_property(cui_Label_coffee_prefix, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Label_coffee_prefix, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_text_font(cui_Label_coffee_prefix, &ui_font_P1_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label_coffee_postfix;
    cui_Label_coffee_postfix = lv_label_create(cui_Container_coffee_name);
    lv_obj_set_width(cui_Label_coffee_postfix, LV_SIZE_CONTENT);   /// 126
    lv_obj_set_height(cui_Label_coffee_postfix, LV_SIZE_CONTENT);    /// 52
    lv_obj_set_align(cui_Label_coffee_postfix, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(cui_Label_coffee_postfix, "macchiato");
    ui_object_set_themeable_style_property(cui_Label_coffee_postfix, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Label_coffee_postfix, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_text_font(cui_Label_coffee_postfix, &ui_font_P1_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Image_right_chevron;
    cui_Image_right_chevron = lv_image_create(cui_Container_selector_);
    lv_image_set_src(cui_Image_right_chevron, &ui_img_266850372);
    lv_obj_set_width(cui_Image_right_chevron, 48);
    lv_obj_set_height(cui_Image_right_chevron, 48);
    lv_obj_set_align(cui_Image_right_chevron, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image_right_chevron, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(cui_Image_right_chevron, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(cui_Image_right_chevron, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_bg_image_src(cui_Image_right_chevron, &ui_img_266850372, LV_PART_MAIN | LV_STATE_PRESSED);
    ui_object_set_themeable_style_property(cui_Image_right_chevron, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Image_right_chevron, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_fg_Primary);
    ui_object_set_themeable_style_property(cui_Image_right_chevron, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Image_right_chevron, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_fg_Primary);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINER_SELECTOR_NUM);
    children[UI_COMP_CONTAINER_SELECTOR_CONTAINER_SELECTOR] = cui_Container_selector;
    children[UI_COMP_CONTAINER_SELECTOR_IMAGE_SELECTED_COFFEE] = cui_Image_selected_coffee;
    children[UI_COMP_CONTAINER_SELECTOR_CONTAINER_SELECTOR_] = cui_Container_selector_;
    children[UI_COMP_CONTAINER_SELECTOR_CONTAINER_SELECTOR__IMAGE_LEFT_CHEVRON] = cui_Image_left_chevron;
    children[UI_COMP_CONTAINER_SELECTOR_CONTAINER_SELECTOR__CONTAINER_COFFEE_NAME] = cui_Container_coffee_name;
    children[UI_COMP_CONTAINER_SELECTOR_CONTAINER_SELECTOR__CONTAINER_COFFEE_NAME_LABEL_COFFEE_PREFIX] =
        cui_Label_coffee_prefix;
    children[UI_COMP_CONTAINER_SELECTOR_CONTAINER_SELECTOR__CONTAINER_COFFEE_NAME_LABEL_COFFEE_POSTFIX] =
        cui_Label_coffee_postfix;
    children[UI_COMP_CONTAINER_SELECTOR_CONTAINER_SELECTOR__IMAGE_RIGHT_CHEVRON] = cui_Image_right_chevron;
    lv_obj_add_event_cb(cui_Container_selector, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Container_selector, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Container_selector_create_hook(cui_Container_selector);
    return cui_Container_selector;
}

