// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: ebike_demo

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings
extern void ui_Settings_screen_init(void);
extern void ui_Settings_screen_destroy(void);
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_Group_Header1;
extern lv_obj_t * ui_Head_Group2;
extern lv_obj_t * ui_Label_Time2;
extern lv_obj_t * ui_LabeL_PM1;
extern lv_obj_t * ui_Label_Temp1;
extern lv_obj_t * ui_Label_Celsius1;
extern lv_obj_t * ui_Label_Battery1;
extern lv_obj_t * ui_Settings_Content;
extern lv_obj_t * ui_Roller;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_Brightness_Group;
extern lv_obj_t * ui_Brightness_Label;
extern void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Brightness_Percent;
extern void ui_event_Volum_On(lv_event_t * e);
extern lv_obj_t * ui_Volum_On;
extern void ui_event_Volume_Off(lv_event_t * e);
extern lv_obj_t * ui_Volume_Off;
extern lv_obj_t * ui_Chart_Group;
extern lv_obj_t * ui_Chart_Label;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_chart_scrollbar;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Chart2_Xaxis;
extern lv_obj_t * ui_Chart2_Yaxis1;
extern lv_obj_t * ui_Chart2_Yaxis2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Group_Max_Speed1;
extern lv_obj_t * ui_Label_Max_Speed1;
extern lv_obj_t * ui_Label_Max_Speed_Number1;
extern lv_obj_t * ui_Label_kmh4;
extern lv_obj_t * ui_Group_AVG_Speed1;
extern lv_obj_t * ui_Label_AVG_Speed1;
extern lv_obj_t * ui_Label_AVG_Speed_Number1;
extern lv_obj_t * ui_Label_kmh5;
extern lv_obj_t * ui_Label_Number6;
extern lv_obj_t * ui_Menu1;
extern void ui_event_BTN_Settings1(lv_event_t * e);
extern lv_obj_t * ui_BTN_Settings1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

