// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_fg_Primary[1] = {0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_fg_Primary[1] = {255};

const ui_theme_variable_t _ui_theme_color_fg_Secondary[1] = {0x353B40};
const ui_theme_variable_t _ui_theme_alpha_fg_Secondary[1] = {255};

const ui_theme_variable_t _ui_theme_color_fg_Disabled[1] = {0x8E989F};
const ui_theme_variable_t _ui_theme_alpha_fg_Disabled[1] = {255};

const ui_theme_variable_t _ui_theme_color_bg_Secondary[1] = {0x303030};
const ui_theme_variable_t _ui_theme_alpha_bg_Secondary[1] = {255};

const ui_theme_variable_t _ui_theme_color_bg_Tertiary[1] = {0x000000};
const ui_theme_variable_t _ui_theme_alpha_bg_Tertiary[1] = {255};

const ui_theme_variable_t _ui_theme_color_overlay_Primary[1] = {0x304149};
const ui_theme_variable_t _ui_theme_alpha_overlay_Primary[1] = {64};

const ui_theme_variable_t _ui_theme_color_border_Primary[1] = {0x6D777E};
const ui_theme_variable_t _ui_theme_alpha_border_Primary[1] = {255};

const ui_theme_variable_t _ui_theme_color_border_Secondary[1] = {0x353B40};
const ui_theme_variable_t _ui_theme_alpha_border_Secondary[1] = {255};

const ui_theme_variable_t _ui_theme_color_Red[1] = {0xE63946};
const ui_theme_variable_t _ui_theme_alpha_Red[1] = {255};

const ui_theme_variable_t _ui_theme_color_Orange[1] = {0xF4A261};
const ui_theme_variable_t _ui_theme_alpha_Orange[1] = {255};

const ui_theme_variable_t _ui_theme_color_Yellow[1] = {0xF9C74F};
const ui_theme_variable_t _ui_theme_alpha_Yellow[1] = {255};

const ui_theme_variable_t _ui_theme_color_Green[1] = {0x39D254};
const ui_theme_variable_t _ui_theme_alpha_Green[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

