// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: 3d_printer

#ifndef UI_SCREEN_3_SETTING_H
#define UI_SCREEN_3_SETTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_3_Setting
extern void ui_Screen_3_Setting_screen_init(void);
extern void ui_Screen_3_Setting_screen_destroy(void);
extern lv_obj_t * ui_Screen_3_Setting;
extern lv_obj_t * ui_Background2;
extern lv_obj_t * ui_Panel_Header2;
extern lv_obj_t * ui_Label_Header2;
extern lv_obj_t * ui_IMG_Wifi2;
extern lv_obj_t * ui_IMG_PC2;
extern lv_obj_t * ui_IMG_USB2;
extern void ui_event_BTN_Menu_Print_S3(lv_event_t * e);
extern lv_obj_t * ui_BTN_Menu_Print_S3;
extern void ui_event_BTN_Menu_Move_S3(lv_event_t * e);
extern lv_obj_t * ui_BTN_Menu_Move_S3;
extern lv_obj_t * ui_BTN_Menu_Setting_S3;
extern lv_obj_t * ui_S1_Content_Panel2;
extern lv_obj_t * ui_Roller_Material;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Roller4;
extern lv_obj_t * ui_Label_Material;
extern lv_obj_t * ui_Roller_Bed_Temp;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Roller3;
extern lv_obj_t * ui_Label_Bed_Temp1;
extern lv_obj_t * ui_Roller_Head_Temp;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Roller2;
extern lv_obj_t * ui_Label_Head_Temp1;
extern lv_obj_t * ui_BTN_Heat_Head;
extern lv_obj_t * ui_Label_Reset22;
extern lv_obj_t * ui_BTN_Heat_Bed;
extern lv_obj_t * ui_Label_Heat_Bed;
extern lv_obj_t * ui_BTN_Remove_Filament;
extern lv_obj_t * ui_Label_Remove_Filament;
extern lv_obj_t * ui_Panel_Slider;
extern void ui_event_Slider_Print_Speed(lv_event_t * e);
extern lv_obj_t * ui_Slider_Print_Speed;
extern lv_obj_t * ui_Label_Print_Speed;
extern lv_obj_t * ui_Label_Print_Speed_Number;
extern lv_obj_t * ui_Swich_Group;
extern lv_obj_t * ui_Label_Light;
extern lv_obj_t * ui_Switch_Light;
extern lv_obj_t * ui_Label_Fan_1;
extern lv_obj_t * ui_Switch_Fan_1;
extern lv_obj_t * ui_Label_Fan_2;
extern lv_obj_t * ui_Switch_Fan_2;
extern lv_obj_t * ui_Label_Fan_3;
extern lv_obj_t * ui_Switch_Fan_3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

