// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: ebike_demo

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_BG1;
extern lv_obj_t * ui_Label_Speed;
extern lv_obj_t * ui_Label_kmh1;
extern void ui_event_Slider_Speed(lv_event_t * e);
extern lv_obj_t * ui_Slider_Speed;
extern void ui_event_Slider_Battery(lv_event_t * e);
extern lv_obj_t * ui_Slider_Battery;
extern lv_obj_t * ui_Group_Battery_Percent;
extern lv_obj_t * ui_Label_Number1;
extern lv_obj_t * ui_Label_Number2;
extern lv_obj_t * ui_Label_Number3;
extern lv_obj_t * ui_Label_Number4;
extern lv_obj_t * ui_Label_Number5;
extern lv_obj_t * ui_Group_Header2;
extern lv_obj_t * ui_Head_Group1;
extern lv_obj_t * ui_Label_Time3;
extern lv_obj_t * ui_LabeL_PM2;
extern lv_obj_t * ui_Label_Temp2;
extern lv_obj_t * ui_Label_Celsius2;
extern lv_obj_t * ui_Label_Battery2;
extern lv_obj_t * ui_Group_Footer;
extern lv_obj_t * ui_Image_Battery_icon;
extern lv_obj_t * ui_Label_Battery_Number;
extern lv_obj_t * ui_Label_Battery_Percent;
extern lv_obj_t * ui_Button_Group;
extern lv_obj_t * ui_BTN_Driving;
extern void ui_event_BTN_BG1(lv_event_t * e);
extern lv_obj_t * ui_BTN_BG1;
extern lv_obj_t * ui_ICN_Driving;
extern lv_obj_t * ui_BTN_Battery;
extern void ui_event_BTN_BG2(lv_event_t * e);
extern lv_obj_t * ui_BTN_BG2;
extern lv_obj_t * ui_ICN_Battery;
extern lv_obj_t * ui_BTN_MAp;
extern void ui_event_BTN_BG3(lv_event_t * e);
extern lv_obj_t * ui_BTN_BG3;
extern lv_obj_t * ui_ICN_Map;
extern lv_obj_t * ui_Group_Driving;
extern lv_obj_t * ui_Group_Title;
extern lv_obj_t * ui_Title_BG;
extern lv_obj_t * ui_Label_Driving_Information;
extern lv_obj_t * ui_Group_Content;
extern lv_obj_t * ui_Group_ODO;
extern lv_obj_t * ui_LabeL_ODO;
extern lv_obj_t * ui_Label_ODO_Number;
extern lv_obj_t * ui_Label_km1;
extern lv_obj_t * ui_Group_Trip;
extern lv_obj_t * ui_Label_Trip;
extern lv_obj_t * ui_Label_Trip_Number;
extern lv_obj_t * ui_Label_km2;
extern lv_obj_t * ui_Group_Max_Speed;
extern lv_obj_t * ui_Label_Max_Speed;
extern lv_obj_t * ui_Label_Max_Speed_Number;
extern lv_obj_t * ui_Label_kmh2;
extern lv_obj_t * ui_Group_AVG_Speed;
extern lv_obj_t * ui_Label_AVG_Speed;
extern lv_obj_t * ui_Label_AVG_Speed_Number;
extern lv_obj_t * ui_Label_kmh3;
extern lv_obj_t * ui_Group_ETA;
extern lv_obj_t * ui_Label_ETA;
extern lv_obj_t * ui_Label_ETA_Number;
extern lv_obj_t * ui_Group_Time;
extern lv_obj_t * ui_Label_Time1;
extern lv_obj_t * ui_Label_Arrival_Time_Number1;
extern lv_obj_t * ui_Group_Battery;
extern lv_obj_t * ui_Group_Title1;
extern lv_obj_t * ui_Title_BG1;
extern lv_obj_t * ui_Label_Battery_Information;
extern lv_obj_t * ui_Group_Content1;
extern lv_obj_t * ui_Group_Charging;
extern lv_obj_t * ui_LabeL_Charging;
extern lv_obj_t * ui_Label_Charging_Number;
extern lv_obj_t * ui_Label_Percent1;
extern lv_obj_t * ui_Group_Distance;
extern lv_obj_t * ui_Label_Distance;
extern lv_obj_t * ui_Label_Distance_Number;
extern lv_obj_t * ui_Label_km4;
extern lv_obj_t * ui_Group_Complete;
extern lv_obj_t * ui_Label_Complete;
extern lv_obj_t * ui_Label_Complete_Number;
extern lv_obj_t * ui_Label_Mins;
extern lv_obj_t * ui_Group_Battery_Indicator;
extern lv_obj_t * ui_Particle_Group;
extern lv_obj_t * ui_Image_Particle1;
extern lv_obj_t * ui_Wave_Group;
extern lv_obj_t * ui_Wave1;
extern lv_obj_t * ui_Image_Particle2;
extern lv_obj_t * ui_Wave2;
extern lv_obj_t * ui_Image_Particle3;
extern lv_obj_t * ui_Image_Battery_BG;
extern lv_obj_t * ui_Image_Flash;
extern lv_obj_t * ui_Group_Pin;
extern lv_obj_t * ui_Group_Title2;
extern lv_obj_t * ui_Title_BG2;
extern lv_obj_t * ui_Label_Unlock;
extern lv_obj_t * ui_Group_Pin1;
extern void ui_event_Button_Pin1(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin1;
extern lv_obj_t * ui_Label_1;
extern lv_obj_t * ui_Pin_Add1;
extern void ui_event_Button_Pin2(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin2;
extern lv_obj_t * ui_Label_2;
extern lv_obj_t * ui_Pin_Add2;
extern void ui_event_Button_Pin3(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin3;
extern lv_obj_t * ui_Label_3;
extern lv_obj_t * ui_Pin_Add3;
extern void ui_event_Button_Pin4(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin4;
extern lv_obj_t * ui_Label_4;
extern lv_obj_t * ui_Pin_Add4;
extern void ui_event_Button_Pin5(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin5;
extern lv_obj_t * ui_Label_5;
extern lv_obj_t * ui_Pin_Add5;
extern void ui_event_Button_Pin6(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin6;
extern lv_obj_t * ui_Label_6;
extern lv_obj_t * ui_Pin_Add6;
extern void ui_event_Button_Pin7(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin7;
extern lv_obj_t * ui_Label_7;
extern lv_obj_t * ui_Pin_Add7;
extern void ui_event_Button_Pin8(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin8;
extern lv_obj_t * ui_Label_8;
extern lv_obj_t * ui_Pin_Add8;
extern void ui_event_Button_Pin9(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin9;
extern lv_obj_t * ui_Label_9;
extern lv_obj_t * ui_Pin_Add9;
extern void ui_event_Button_PinX(lv_event_t * e);
extern lv_obj_t * ui_Button_PinX;
extern lv_obj_t * ui_Pin_Add10;
extern lv_obj_t * ui_Image_X;
extern void ui_event_Button_Pin0(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin0;
extern lv_obj_t * ui_Label_0;
extern lv_obj_t * ui_Pin_Add11;
extern void ui_event_Button_PinX1(lv_event_t * e);
extern lv_obj_t * ui_Button_PinX1;
extern lv_obj_t * ui_Pin_Add12;
extern lv_obj_t * ui_Image_Ok;
extern lv_obj_t * ui_Group_Map;
extern lv_obj_t * ui_Map_Bg;
extern lv_obj_t * ui_Marker_Group;
extern lv_obj_t * ui_GPS_Root2;
extern lv_obj_t * ui_GPS_Root1;
extern lv_obj_t * ui_Gps_Knob_Bg;
extern lv_obj_t * ui_GPS_Knob;
extern lv_obj_t * ui_Distance_Group;
extern lv_obj_t * ui_Distance;
extern lv_obj_t * ui_Label_Max_Speed_Number2;
extern lv_obj_t * ui_Label_kmh6;
extern lv_obj_t * ui_Label_Max_Speed2;
extern lv_obj_t * ui_Next_Group;
extern lv_obj_t * ui_Next;
extern lv_obj_t * ui_Label_Next;
extern lv_obj_t * ui_Label_Next_Distance;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Speed_Number_2;
extern lv_obj_t * ui_Speed_Number_1;
extern lv_obj_t * ui_Menu;
extern void ui_event_BTN_Settings(lv_event_t * e);
extern lv_obj_t * ui_BTN_Settings;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

