// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#include "../ui.h"

void ui_event_comp_Container_home_sliders_Slider_slider_length(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_Container_home_sliders = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(comp_Container_home_sliders[UI_COMP_CONTAINER_HOME_SLIDERS_LABEL_LENGTH], target, "Length ",
                                  "00 ml");
    }
}

// COMPONENT home sliders

lv_obj_t * ui_Container_home_sliders_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Container_home_sliders;
    cui_Container_home_sliders = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Container_home_sliders);
    lv_obj_set_width(cui_Container_home_sliders, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(cui_Container_home_sliders, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Container_home_sliders, 0);
    lv_obj_set_y(cui_Container_home_sliders, -2);
    lv_obj_set_align(cui_Container_home_sliders, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(cui_Container_home_sliders, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_Container_home_sliders, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_Container_home_sliders, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(cui_Container_home_sliders, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Container_home_sliders, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label_length;
    cui_Label_length = lv_label_create(cui_Container_home_sliders);
    lv_obj_set_width(cui_Label_length, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label_length, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label_length, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label_length, "Length 100 ml");
    lv_obj_add_flag(cui_Label_length, LV_OBJ_FLAG_HIDDEN);     /// Flags
    ui_object_set_themeable_style_property(cui_Label_length, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Label_length, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_text_font(cui_Label_length, &ui_font_P1_medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label_strength;
    cui_Label_strength = lv_label_create(cui_Container_home_sliders);
    lv_obj_set_width(cui_Label_strength, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label_strength, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label_strength, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label_strength, "Coffee strength");
    ui_object_set_themeable_style_property(cui_Label_strength, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Label_strength, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_text_font(cui_Label_strength, &ui_font_P1_medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Container_strength_container;
    cui_Container_strength_container = lv_obj_create(cui_Container_home_sliders);
    lv_obj_remove_style_all(cui_Container_strength_container);
    lv_obj_set_width(cui_Container_strength_container, 219);
    lv_obj_set_height(cui_Container_strength_container, 48);
    lv_obj_set_align(cui_Container_strength_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Container_strength_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Container_strength_container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_Container_strength_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(cui_Container_strength_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Container_strength_container, 9, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Image_single_bean;
    cui_Image_single_bean = lv_image_create(cui_Container_strength_container);
    lv_image_set_src(cui_Image_single_bean, &ui_img_disabledbean_png);
    lv_obj_set_width(cui_Image_single_bean, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image_single_bean, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Image_single_bean, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image_single_bean, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(cui_Image_single_bean, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(cui_Image_single_bean, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Image_single_bean, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_fg_Primary);

    lv_obj_t * cui_Slider_slider_strength;
    cui_Slider_slider_strength = lv_slider_create(cui_Container_strength_container);
    lv_slider_set_range(cui_Slider_slider_strength, 0, 3);
    lv_slider_set_value(cui_Slider_slider_strength, 1, LV_ANIM_OFF);
    if(lv_slider_get_mode(cui_Slider_slider_strength) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            cui_Slider_slider_strength, 0, LV_ANIM_OFF);
    lv_obj_set_width(cui_Slider_slider_strength, 162);
    lv_obj_set_height(cui_Slider_slider_strength, 48);
    lv_obj_set_align(cui_Slider_slider_strength, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(cui_Slider_slider_strength, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Slider_slider_strength, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(cui_Slider_slider_strength, &ui_img_beans_white_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Slider_slider_strength, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_fg_Disabled);
    ui_object_set_themeable_style_property(cui_Slider_slider_strength, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_fg_Disabled);

    lv_obj_set_style_bg_color(cui_Slider_slider_strength, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Slider_slider_strength, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(cui_Slider_slider_strength, &ui_img_beans_white_png,
                                  LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Slider_slider_strength, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Slider_slider_strength, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_fg_Primary);

    lv_obj_set_style_bg_color(cui_Slider_slider_strength, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Slider_slider_strength, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(cui_Slider_slider_strength,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(cui_Slider_slider_strength,
                                                                                  lv_obj_get_style_pad_right(cui_Slider_slider_strength, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_t * cui_Container_length_container;
    cui_Container_length_container = lv_obj_create(cui_Container_home_sliders);
    lv_obj_remove_style_all(cui_Container_length_container);
    lv_obj_set_width(cui_Container_length_container, 219);
    lv_obj_set_height(cui_Container_length_container, 48);
    lv_obj_set_align(cui_Container_length_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Container_length_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Container_length_container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(cui_Container_length_container, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(cui_Container_length_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(cui_Container_length_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Container_length_container, 9, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Image_single_cup;
    cui_Image_single_cup = lv_image_create(cui_Container_length_container);
    lv_image_set_src(cui_Image_single_cup, &ui_img_cup_png);
    lv_obj_set_width(cui_Image_single_cup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image_single_cup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Image_single_cup, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image_single_cup, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(cui_Image_single_cup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Slider_slider_length;
    cui_Slider_slider_length = lv_slider_create(cui_Container_length_container);
    lv_slider_set_range(cui_Slider_slider_length, 1, 4);
    lv_slider_set_value(cui_Slider_slider_length, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(cui_Slider_slider_length) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            cui_Slider_slider_length, 0, LV_ANIM_OFF);
    lv_obj_set_width(cui_Slider_slider_length, 162);
    lv_obj_set_height(cui_Slider_slider_length, 48);
    lv_obj_set_align(cui_Slider_slider_length, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Slider_slider_length, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Slider_slider_length, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(cui_Slider_slider_length, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Slider_slider_length, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(cui_Slider_slider_length, &ui_img_cups_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Slider_slider_length, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_fg_Disabled);
    ui_object_set_themeable_style_property(cui_Slider_slider_length, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_fg_Disabled);

    lv_obj_set_style_bg_color(cui_Slider_slider_length, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Slider_slider_length, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(cui_Slider_slider_length, &ui_img_cups_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(cui_Slider_slider_length, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Slider_slider_length, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_Slider_slider_length, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Slider_slider_length, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(cui_Slider_slider_length,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(cui_Slider_slider_length,
                                                                                  lv_obj_get_style_pad_right(cui_Slider_slider_length, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINER_HOME_SLIDERS_NUM);
    children[UI_COMP_CONTAINER_HOME_SLIDERS_CONTAINER_HOME_SLIDERS] = cui_Container_home_sliders;
    children[UI_COMP_CONTAINER_HOME_SLIDERS_LABEL_LENGTH] = cui_Label_length;
    children[UI_COMP_CONTAINER_HOME_SLIDERS_LABEL_STRENGTH] = cui_Label_strength;
    children[UI_COMP_CONTAINER_HOME_SLIDERS_CONTAINER_STRENGTH_CONTAINER] = cui_Container_strength_container;
    children[UI_COMP_CONTAINER_HOME_SLIDERS_CONTAINER_STRENGTH_CONTAINER_IMAGE_SINGLE_BEAN] = cui_Image_single_bean;
    children[UI_COMP_CONTAINER_HOME_SLIDERS_CONTAINER_STRENGTH_CONTAINER_SLIDER_SLIDER_STRENGTH] =
        cui_Slider_slider_strength;
    children[UI_COMP_CONTAINER_HOME_SLIDERS_CONTAINER_LENGTH_CONTAINER] = cui_Container_length_container;
    children[UI_COMP_CONTAINER_HOME_SLIDERS_CONTAINER_LENGTH_CONTAINER_IMAGE_SINGLE_CUP] = cui_Image_single_cup;
    children[UI_COMP_CONTAINER_HOME_SLIDERS_CONTAINER_LENGTH_CONTAINER_SLIDER_SLIDER_LENGTH] = cui_Slider_slider_length;
    lv_obj_add_event_cb(cui_Container_home_sliders, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Container_home_sliders, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_Slider_slider_length, ui_event_comp_Container_home_sliders_Slider_slider_length, LV_EVENT_ALL,
                        children);
    ui_comp_Container_home_sliders_create_hook(cui_Container_home_sliders);
    return cui_Container_home_sliders;
}

