// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#ifndef _UI_COMP_PARAMETER_H
#define _UI_COMP_PARAMETER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT parameter
#define UI_COMP_CONTAINER_PARAMETER_CONTAINER_PARAMETER 0
#define UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER 1
#define UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY 2
#define UI_COMP_CONTAINER_PARAMETER_IMAGE_SLIDER_ICON 3
#define _UI_COMP_CONTAINER_PARAMETER_NUM 4
lv_obj_t * ui_Container_parameter_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
