// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#ifndef _UI_COMP_SEPARATOR_H
#define _UI_COMP_SEPARATOR_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT separator
#define UI_COMP_CONTAINER_SEPARATOR_CONTAINER_SEPARATOR 0
#define UI_COMP_CONTAINER_SEPARATOR_PANEL_TOP_PANEL 1
#define UI_COMP_CONTAINER_SEPARATOR_PANEL_BOTTOM_PANEL 2
#define _UI_COMP_CONTAINER_SEPARATOR_NUM 3
lv_obj_t * ui_Container_separator_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
