// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#ifndef _UI_COMP_STEPS_H
#define _UI_COMP_STEPS_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT steps
#define UI_COMP_CONTAINER_STEPS_CONTAINER_STEPS 0
#define UI_COMP_CONTAINER_STEPS_PANEL_LEFT_POINT 1
#define UI_COMP_CONTAINER_STEPS_PANEL_RIGHT_POINT 2
#define _UI_COMP_CONTAINER_STEPS_NUM 3
lv_obj_t * ui_Container_steps_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
