// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#include "../ui.h"

// COMPONENT header

lv_obj_t * ui_Container_header_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Container_header;
    cui_Container_header = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Container_header);
    lv_obj_set_height(cui_Container_header, 83);
    lv_obj_set_width(cui_Container_header, lv_pct(100));
    lv_obj_set_align(cui_Container_header, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(cui_Container_header, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Container_header_panel;
    cui_Container_header_panel = lv_obj_create(cui_Container_header);
    lv_obj_remove_style_all(cui_Container_header_panel);
    lv_obj_set_height(cui_Container_header_panel, 79);
    lv_obj_set_width(cui_Container_header_panel, lv_pct(100));
    lv_obj_set_align(cui_Container_header_panel, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(cui_Container_header_panel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Container_header_panel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Container_header_panel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(cui_Container_header_panel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bg_Secondary);
    ui_object_set_themeable_style_property(cui_Container_header_panel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bg_Secondary);
    lv_obj_set_style_pad_left(cui_Container_header_panel, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Container_header_panel, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Container_header_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Container_header_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Container_left_container;
    cui_Container_left_container = lv_obj_create(cui_Container_header_panel);
    lv_obj_remove_style_all(cui_Container_left_container);
    lv_obj_set_width(cui_Container_left_container, 173);
    lv_obj_set_height(cui_Container_left_container, LV_SIZE_CONTENT);    /// 50
    lv_obj_remove_flag(cui_Container_left_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Container_back_btn;
    cui_Container_back_btn = lv_obj_create(cui_Container_left_container);
    lv_obj_remove_style_all(cui_Container_back_btn);
    lv_obj_set_width(cui_Container_back_btn, 60);
    lv_obj_set_height(cui_Container_back_btn, 60);
    lv_obj_remove_flag(cui_Container_back_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Container_back_btn, 400, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(cui_Container_back_btn, &ui_img_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Container_back_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_border_Primary);
    ui_object_set_themeable_style_property(cui_Container_back_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_border_Primary);
    lv_obj_set_style_border_width(cui_Container_back_btn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(cui_Container_back_btn, &ui_img_arrow_png, LV_PART_MAIN | LV_STATE_PRESSED);
    ui_object_set_themeable_style_property(cui_Container_back_btn, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_fg_Disabled);
    ui_object_set_themeable_style_property(cui_Container_back_btn, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_fg_Disabled);
    ui_object_set_themeable_style_property(cui_Container_back_btn, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Container_back_btn, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_border_width(cui_Container_back_btn, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_src(cui_Container_back_btn, &ui_img_arrow_png, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_image_opa(cui_Container_back_btn, 85, LV_PART_MAIN | LV_STATE_DISABLED);
    ui_object_set_themeable_style_property(cui_Container_back_btn, LV_PART_MAIN | LV_STATE_DISABLED,
                                           LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_fg_Disabled);
    ui_object_set_themeable_style_property(cui_Container_back_btn, LV_PART_MAIN | LV_STATE_DISABLED,
                                           LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_fg_Disabled);

    lv_obj_t * cui_Label_title;
    cui_Label_title = lv_label_create(cui_Container_header_panel);
    lv_obj_set_width(cui_Label_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label_title, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_Label_title, "Customize");
    ui_object_set_themeable_style_property(cui_Label_title, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Label_title, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_text_font(cui_Label_title, &ui_font_H2_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Container_right_container;
    cui_Container_right_container = lv_obj_create(cui_Container_header_panel);
    lv_obj_remove_style_all(cui_Container_right_container);
    lv_obj_set_width(cui_Container_right_container, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(cui_Container_right_container, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(cui_Container_right_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Container_right_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Container_right_container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_Container_right_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(cui_Container_right_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Container_right_container, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Container_status_icons;
    cui_Container_status_icons = lv_obj_create(cui_Container_right_container);
    lv_obj_remove_style_all(cui_Container_status_icons);
    lv_obj_set_height(cui_Container_status_icons, 60);
    lv_obj_set_width(cui_Container_status_icons, LV_SIZE_CONTENT);   /// 93
    lv_obj_set_align(cui_Container_status_icons, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Container_status_icons, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_Container_status_icons, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Container_status_icons, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(cui_Container_status_icons, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Container_status_icons, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Container_status_icons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Container_status_icons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_Container_status_icons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Container_status_icons, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Container_top_separators;
    cui_Container_top_separators = lv_obj_create(cui_Container_status_icons);
    lv_obj_remove_style_all(cui_Container_top_separators);
    lv_obj_set_width(cui_Container_top_separators, 93);
    lv_obj_set_height(cui_Container_top_separators, 1);
    lv_obj_set_align(cui_Container_top_separators, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(cui_Container_top_separators, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Container_top_separators, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_Container_top_separators, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Panel_left_panel;
    cui_Panel_left_panel = lv_obj_create(cui_Container_top_separators);
    lv_obj_set_height(cui_Panel_left_panel, 1);
    lv_obj_set_flex_grow(cui_Panel_left_panel, 1);
    lv_obj_set_align(cui_Panel_left_panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Panel_left_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Panel_left_panel, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel_left_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_Panel_left_panel, lv_color_hex(0x797F82), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(cui_Panel_left_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(cui_Panel_left_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(cui_Panel_left_panel, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel_right_panel;
    cui_Panel_right_panel = lv_obj_create(cui_Container_top_separators);
    lv_obj_set_height(cui_Panel_right_panel, 1);
    lv_obj_set_flex_grow(cui_Panel_right_panel, 1);
    lv_obj_set_align(cui_Panel_right_panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Panel_right_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Panel_right_panel, lv_color_hex(0x797F82), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel_right_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_Panel_right_panel, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(cui_Panel_right_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(cui_Panel_right_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(cui_Panel_right_panel, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Container_icons_row;
    cui_Container_icons_row = lv_obj_create(cui_Container_status_icons);
    lv_obj_remove_style_all(cui_Container_icons_row);
    lv_obj_set_height(cui_Container_icons_row, 50);
    lv_obj_set_width(cui_Container_icons_row, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(cui_Container_icons_row, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Container_icons_row, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Container_icons_row, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Container_icons_row, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Image_ble;
    cui_Image_ble = lv_image_create(cui_Container_icons_row);
    lv_image_set_src(cui_Image_ble, &ui_img_ble_png);
    lv_obj_set_width(cui_Image_ble, 40);
    lv_obj_set_height(cui_Image_ble, 40);
    lv_obj_set_align(cui_Image_ble, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image_ble, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(cui_Image_ble, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(cui_Image_ble, LV_IMAGE_ALIGN_TILE);
    ui_object_set_themeable_style_property(cui_Image_ble, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_fg_Disabled);
    ui_object_set_themeable_style_property(cui_Image_ble, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_fg_Disabled);

    lv_obj_t * cui_Image_wifi;
    cui_Image_wifi = lv_image_create(cui_Container_icons_row);
    lv_image_set_src(cui_Image_wifi, &ui_img_wifi_png);
    lv_obj_set_width(cui_Image_wifi, 40);
    lv_obj_set_height(cui_Image_wifi, 40);
    lv_obj_set_align(cui_Image_wifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image_wifi, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(cui_Image_wifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(cui_Image_wifi, LV_IMAGE_ALIGN_TILE);
    ui_object_set_themeable_style_property(cui_Image_wifi, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Image_wifi, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_fg_Primary);

    lv_obj_t * cui_Container_bottom_separators;
    cui_Container_bottom_separators = lv_obj_create(cui_Container_status_icons);
    lv_obj_remove_style_all(cui_Container_bottom_separators);
    lv_obj_set_width(cui_Container_bottom_separators, 93);
    lv_obj_set_height(cui_Container_bottom_separators, 1);
    lv_obj_set_align(cui_Container_bottom_separators, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(cui_Container_bottom_separators, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Container_bottom_separators, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_Container_bottom_separators, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Panel_left_panel2;
    cui_Panel_left_panel2 = lv_obj_create(cui_Container_bottom_separators);
    lv_obj_set_height(cui_Panel_left_panel2, 1);
    lv_obj_set_flex_grow(cui_Panel_left_panel2, 1);
    lv_obj_set_align(cui_Panel_left_panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Panel_left_panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Panel_left_panel2, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel_left_panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_Panel_left_panel2, lv_color_hex(0x797F82), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(cui_Panel_left_panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(cui_Panel_left_panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(cui_Panel_left_panel2, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel_right_panel1;
    cui_Panel_right_panel1 = lv_obj_create(cui_Container_bottom_separators);
    lv_obj_set_height(cui_Panel_right_panel1, 1);
    lv_obj_set_flex_grow(cui_Panel_right_panel1, 1);
    lv_obj_set_align(cui_Panel_right_panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Panel_right_panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Panel_right_panel1, lv_color_hex(0x797F82), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel_right_panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_Panel_right_panel1, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(cui_Panel_right_panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(cui_Panel_right_panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(cui_Panel_right_panel1, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Container_settings;
    cui_Container_settings = lv_obj_create(cui_Container_right_container);
    lv_obj_remove_style_all(cui_Container_settings);
    lv_obj_set_width(cui_Container_settings, 60);
    lv_obj_set_height(cui_Container_settings, 60);
    lv_obj_set_align(cui_Container_settings, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Container_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Container_settings, 400, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(cui_Container_settings, &ui_img_settings_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Container_settings, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_border_Primary);
    ui_object_set_themeable_style_property(cui_Container_settings, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_border_Primary);
    lv_obj_set_style_border_width(cui_Container_settings, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(cui_Container_settings, &ui_img_settings_png, LV_PART_MAIN | LV_STATE_PRESSED);
    ui_object_set_themeable_style_property(cui_Container_settings, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_fg_Disabled);
    ui_object_set_themeable_style_property(cui_Container_settings, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_fg_Disabled);
    ui_object_set_themeable_style_property(cui_Container_settings, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Container_settings, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_border_width(cui_Container_settings, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_src(cui_Container_settings, &ui_img_settings_png, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_image_opa(cui_Container_settings, 85, LV_PART_MAIN | LV_STATE_DISABLED);
    ui_object_set_themeable_style_property(cui_Container_settings, LV_PART_MAIN | LV_STATE_DISABLED,
                                           LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_fg_Disabled);
    ui_object_set_themeable_style_property(cui_Container_settings, LV_PART_MAIN | LV_STATE_DISABLED,
                                           LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_fg_Disabled);

    lv_obj_t * cui_Container_header_border;
    cui_Container_header_border = lv_obj_create(cui_Container_header);
    lv_obj_remove_style_all(cui_Container_header_border);
    lv_obj_set_width(cui_Container_header_border, lv_pct(100));
    lv_obj_set_height(cui_Container_header_border, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(cui_Container_header_border, 0);
    lv_obj_set_y(cui_Container_header_border, 79);
    lv_obj_set_align(cui_Container_header_border, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(cui_Container_header_border, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Container_header_border, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_Container_header_border, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Panel_left_line;
    cui_Panel_left_line = lv_obj_create(cui_Container_header_border);
    lv_obj_set_height(cui_Panel_left_line, 4);
    lv_obj_set_flex_grow(cui_Panel_left_line, 1);
    lv_obj_set_x(cui_Panel_left_line, 0);
    lv_obj_set_y(cui_Panel_left_line, 79);
    lv_obj_set_align(cui_Panel_left_line, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(cui_Panel_left_line, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Panel_left_line, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel_left_line, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_Panel_left_line, lv_color_hex(0x797F82), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(cui_Panel_left_line, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(cui_Panel_left_line, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(cui_Panel_left_line, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel_right_line;
    cui_Panel_right_line = lv_obj_create(cui_Container_header_border);
    lv_obj_set_height(cui_Panel_right_line, 4);
    lv_obj_set_flex_grow(cui_Panel_right_line, 1);
    lv_obj_set_x(cui_Panel_right_line, 0);
    lv_obj_set_y(cui_Panel_right_line, 79);
    lv_obj_set_align(cui_Panel_right_line, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(cui_Panel_right_line, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Panel_right_line, lv_color_hex(0x797F82), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel_right_line, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_Panel_right_line, lv_color_hex(0x363C41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(cui_Panel_right_line, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(cui_Panel_right_line, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(cui_Panel_right_line, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINER_HEADER_NUM);
    children[UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER] = cui_Container_header;
    children[UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL] = cui_Container_header_panel;
    children[UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_LEFT_CONTAINER] = cui_Container_left_container;
    children[UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_LEFT_CONTAINER_CONTAINER_BACK_BTN] =
        cui_Container_back_btn;
    children[UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_LABEL_TITLE] = cui_Label_title;
    children[UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER] = cui_Container_right_container;
    children[UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_STATUS_ICONS] =
        cui_Container_status_icons;
    children[UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_STATUS_ICONS_CONTAINER_TOP_SEPARATORS]
        = cui_Container_top_separators;
    children[UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_STATUS_ICONS_CONTAINER_TOP_SEPARATORS_PANEL_LEFT_PANEL]
        = cui_Panel_left_panel;
    children[UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_STATUS_ICONS_CONTAINER_TOP_SEPARATORS_PANEL_RIGHT_PANEL]
        = cui_Panel_right_panel;
    children[UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_STATUS_ICONS_CONTAINER_ICONS_ROW]
        = cui_Container_icons_row;
    children[UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_STATUS_ICONS_CONTAINER_ICONS_ROW_IMAGE_BLE]
        = cui_Image_ble;
    children[UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_STATUS_ICONS_CONTAINER_ICONS_ROW_IMAGE_WIFI]
        = cui_Image_wifi;
    children[UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_STATUS_ICONS_CONTAINER_BOTTOM_SEPARATORS]
        = cui_Container_bottom_separators;
    children[UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_STATUS_ICONS_CONTAINER_BOTTOM_SEPARATORS_PANEL_LEFT_PANEL2]
        = cui_Panel_left_panel2;
    children[UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_STATUS_ICONS_CONTAINER_BOTTOM_SEPARATORS_PANEL_RIGHT_PANEL1]
        = cui_Panel_right_panel1;
    children[UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_SETTINGS] =
        cui_Container_settings;
    children[UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_BORDER] = cui_Container_header_border;
    children[UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_BORDER_PANEL_LEFT_LINE] = cui_Panel_left_line;
    children[UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_BORDER_PANEL_RIGHT_LINE] = cui_Panel_right_line;
    lv_obj_add_event_cb(cui_Container_header, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Container_header, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Container_header_create_hook(cui_Container_header);
    return cui_Container_header;
}

