// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#ifndef _UI_COMP_CTA_CONTAINER_H
#define _UI_COMP_CTA_CONTAINER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT CTA container
#define UI_COMP_CONTAINER_CTA_CONTAINER_CONTAINER_CTA_CONTAINER 0
#define UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL 1
#define UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL_LABEL_EXCLAMATION 2
#define UI_COMP_CONTAINER_CTA_CONTAINER_LABEL_EXTRACT 3
#define _UI_COMP_CONTAINER_CTA_CONTAINER_NUM 4
lv_obj_t * ui_Container_CTA_container_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
