// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#include "../ui.h"

void ui_comp_Button_Button_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Container_CTA_container_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Container_header_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Container_home_sliders_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Container_homeslider_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Container_parameter_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Container_progress_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Panel_ready_button_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Container_selector_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Container_separator_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Slider_Slider1_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Container_Slider3_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Container_steps_create_hook(lv_obj_t * comp)
{
}
