// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#ifndef _UI_COMP_BUTTON_H
#define _UI_COMP_BUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Button
#define UI_COMP_BUTTON_BUTTON_BUTTON_BUTTON 0
#define UI_COMP_BUTTON_BUTTON_IMAGE_BTN_IMG 1
#define UI_COMP_BUTTON_BUTTON_LABEL_BTN_LABEL 2
#define _UI_COMP_BUTTON_BUTTON_NUM 3
lv_obj_t * ui_Button_Button_create(lv_obj_t * comp_parent);
void ui_event_comp_Button_Button_Button_Button(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
