// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#ifndef _UI_COMP_READY_BUTTON_H
#define _UI_COMP_READY_BUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ready button
#define UI_COMP_PANEL_READY_BUTTON_PANEL_READY_BUTTON 0
#define _UI_COMP_PANEL_READY_BUTTON_NUM 1
lv_obj_t * ui_Panel_ready_button_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
