// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#include "../ui.h"

void ui_event_comp_Button_Button_Button_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_Button_Button = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(comp_Button_Button[UI_COMP_BUTTON_BUTTON_IMAGE_BTN_IMG], LV_STATE_PRESSED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_state_modify(comp_Button_Button[UI_COMP_BUTTON_BUTTON_IMAGE_BTN_IMG], LV_STATE_PRESSED, _UI_MODIFY_STATE_REMOVE);
    }
}

// COMPONENT Button

lv_obj_t * ui_Button_Button_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Button_Button;
    cui_Button_Button = lv_button_create(comp_parent);
    lv_obj_set_width(cui_Button_Button, 398);
    lv_obj_set_height(cui_Button_Button, 80);
    lv_obj_set_align(cui_Button_Button, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Button_Button, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Button_Button, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_Button_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Button_Button, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Button_Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fg_Secondary);
    ui_object_set_themeable_style_property(cui_Button_Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fg_Secondary);
    ui_object_set_themeable_style_property(cui_Button_Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Button_Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_border_width(cui_Button_Button, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_Button_Button, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Button_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Button_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Button_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_Button_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Button_Button, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Button_Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Button_Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_text_font(cui_Button_Button, &ui_font_P1_bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Button_Button, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Button_Button, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fg_Primary);
    ui_object_set_themeable_style_property(cui_Button_Button, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_border_Secondary);
    ui_object_set_themeable_style_property(cui_Button_Button, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_border_Secondary);
    lv_obj_set_style_border_width(cui_Button_Button, 4, LV_PART_MAIN | LV_STATE_CHECKED);
    ui_object_set_themeable_style_property(cui_Button_Button, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Button_Button, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_shadow_width(cui_Button_Button, 40, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(cui_Button_Button, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_offset_x(cui_Button_Button, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_offset_y(cui_Button_Button, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    ui_object_set_themeable_style_property(cui_Button_Button, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_fg_Secondary);
    ui_object_set_themeable_style_property(cui_Button_Button, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_fg_Secondary);
    ui_object_set_themeable_style_property(cui_Button_Button, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Button_Button, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fg_Primary);
    ui_object_set_themeable_style_property(cui_Button_Button, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_border_Secondary);
    ui_object_set_themeable_style_property(cui_Button_Button, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_border_Secondary);
    lv_obj_set_style_border_width(cui_Button_Button, 4, LV_PART_MAIN | LV_STATE_PRESSED);
    ui_object_set_themeable_style_property(cui_Button_Button, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Button_Button, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_shadow_width(cui_Button_Button, 40, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(cui_Button_Button, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    ui_object_set_themeable_style_property(cui_Button_Button, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_fg_Secondary);
    ui_object_set_themeable_style_property(cui_Button_Button, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_fg_Secondary);

    lv_obj_t * cui_Image_btn_img;
    cui_Image_btn_img = lv_image_create(cui_Button_Button);
    lv_image_set_src(cui_Image_btn_img, &ui_img_standby_png);
    lv_obj_set_width(cui_Image_btn_img, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image_btn_img, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Image_btn_img, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(cui_Image_btn_img, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(cui_Image_btn_img, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(cui_Image_btn_img, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Image_btn_img, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_fg_Primary);
    ui_object_set_themeable_style_property(cui_Image_btn_img, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_fg_Secondary);
    ui_object_set_themeable_style_property(cui_Image_btn_img, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_fg_Secondary);
    ui_object_set_themeable_style_property(cui_Image_btn_img, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_fg_Secondary);
    ui_object_set_themeable_style_property(cui_Image_btn_img, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_fg_Secondary);

    lv_obj_t * cui_Label_btn_label;
    cui_Label_btn_label = lv_label_create(cui_Button_Button);
    lv_obj_set_width(cui_Label_btn_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label_btn_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label_btn_label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_Label_btn_label, "Stand-by time");

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON_BUTTON_NUM);
    children[UI_COMP_BUTTON_BUTTON_BUTTON_BUTTON] = cui_Button_Button;
    children[UI_COMP_BUTTON_BUTTON_IMAGE_BTN_IMG] = cui_Image_btn_img;
    children[UI_COMP_BUTTON_BUTTON_LABEL_BTN_LABEL] = cui_Label_btn_label;
    lv_obj_add_event_cb(cui_Button_Button, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Button_Button, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_Button_Button, ui_event_comp_Button_Button_Button_Button, LV_EVENT_ALL, children);
    ui_comp_Button_Button_create_hook(cui_Button_Button);
    return cui_Button_Button;
}

