// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#include "../ui.h"

// COMPONENT CTA container

lv_obj_t * ui_Container_CTA_container_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Container_CTA_container;
    cui_Container_CTA_container = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Container_CTA_container);
    lv_obj_set_height(cui_Container_CTA_container, lv_pct(100));
    lv_obj_set_flex_grow(cui_Container_CTA_container, 2);
    lv_obj_set_align(cui_Container_CTA_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Container_CTA_container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_Container_CTA_container, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Container_CTA_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(cui_Container_CTA_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Container_CTA_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Container_CTA_container, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Container_CTA_container, 44, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_Container_CTA_container, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Container_CTA_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel_circle_panel;
    cui_Panel_circle_panel = lv_obj_create(cui_Container_CTA_container);
    lv_obj_set_width(cui_Panel_circle_panel, 120);
    lv_obj_set_height(cui_Panel_circle_panel, 120);
    lv_obj_set_align(cui_Panel_circle_panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Panel_circle_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Panel_circle_panel, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Panel_circle_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel_circle_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(cui_Panel_circle_panel, &ui_img_play_button_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(cui_Panel_circle_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Panel_circle_panel, lv_color_hex(0x353B40), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Panel_circle_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Panel_circle_panel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Panel_circle_panel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Panel_circle_panel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_shadow_width(cui_Panel_circle_panel, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(cui_Panel_circle_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Panel_circle_panel, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fg_Secondary);
    ui_object_set_themeable_style_property(cui_Panel_circle_panel, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fg_Secondary);
    lv_obj_set_style_bg_image_src(cui_Panel_circle_panel, &ui_img_play_button_png, LV_PART_MAIN | LV_STATE_PRESSED);
    ui_object_set_themeable_style_property(cui_Panel_circle_panel, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Panel_circle_panel, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_fg_Primary);
    ui_object_set_themeable_style_property(cui_Panel_circle_panel, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Panel_circle_panel, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_border_width(cui_Panel_circle_panel, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(cui_Panel_circle_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(cui_Panel_circle_panel, 86, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_image_src(cui_Panel_circle_panel, &ui_img_play_button_png, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_image_opa(cui_Panel_circle_panel, 86, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_border_color(cui_Panel_circle_panel, lv_color_hex(0x353B40), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_border_opa(cui_Panel_circle_panel, 255, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_shadow_color(cui_Panel_circle_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_shadow_opa(cui_Panel_circle_panel, 86, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_t * cui_Label_exclamation;
    cui_Label_exclamation = lv_label_create(cui_Panel_circle_panel);
    lv_obj_set_width(cui_Label_exclamation, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label_exclamation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label_exclamation, 0);
    lv_obj_set_y(cui_Label_exclamation, 4);
    lv_obj_set_align(cui_Label_exclamation, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label_exclamation, "!");
    lv_obj_add_flag(cui_Label_exclamation, LV_OBJ_FLAG_HIDDEN);     /// Flags
    ui_object_set_themeable_style_property(cui_Label_exclamation, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Label_exclamation, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_text_font(cui_Label_exclamation, &ui_font_exclamation, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label_extract;
    cui_Label_extract = lv_label_create(cui_Container_CTA_container);
    lv_obj_set_width(cui_Label_extract, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label_extract, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label_extract, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label_extract, "Next");
    ui_object_set_themeable_style_property(cui_Label_extract, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(cui_Label_extract, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_text_font(cui_Label_extract, &ui_font_H3_bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(cui_Label_extract, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(cui_Label_extract, 150, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINER_CTA_CONTAINER_NUM);
    children[UI_COMP_CONTAINER_CTA_CONTAINER_CONTAINER_CTA_CONTAINER] = cui_Container_CTA_container;
    children[UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL] = cui_Panel_circle_panel;
    children[UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL_LABEL_EXCLAMATION] = cui_Label_exclamation;
    children[UI_COMP_CONTAINER_CTA_CONTAINER_LABEL_EXTRACT] = cui_Label_extract;
    lv_obj_add_event_cb(cui_Container_CTA_container, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Container_CTA_container, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Container_CTA_container_create_hook(cui_Container_CTA_container);
    return cui_Container_CTA_container;
}

