// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#ifndef _CAFFEE_MACHINE_UI_H
#define _CAFFEE_MACHINE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen_Splash_screen.h"
#include "screens/ui_Screen_Home.h"
#include "screens/ui_Screen_Home_ristretto.h"
#include "screens/ui_Screen_Home_espresso.h"
#include "screens/ui_Screen_Customize.h"
#include "screens/ui_Screen_Customize2.h"
#include "screens/ui_Screen_Brewing.h"
#include "screens/ui_Screen_Brewing_Done.h"
#include "screens/ui_Screen_Settings.h"
#include "screens/ui_Screen_Add_water.h"
#include "screens/ui_Screen_Add_coffee.h"
#include "screens/ui_Screen_Ready.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * left_in_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * left_out_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * coffeeleft_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * progress_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * with_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * top_on_slider_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * icons_bottom_on_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * right_in_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * top_off_slider_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * top_on_alert_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * enjoy_bottom_on_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * enjoybtn_top_on_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * enjoybtn_top_off_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * enjoy_bottom_off_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * icons_bottom_off_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * num_bottom_on_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * num_bottom_off_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * right_off_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * top_off_alert_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * refill_bottom_on_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * refill_bottom_off_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * vector_top_on_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * vector_top_off_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * min_top_on_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * min_top_off_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * home_slider_top_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * home_slider_bottom_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * wave_loop_fg_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * wave_loop_bg_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * rotate_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * with_progress_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * latte_close_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui_Startevents____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bg_png);    // assets/BG.png
LV_IMG_DECLARE(ui_img_shape1_png);    // assets/shape1.png
LV_IMG_DECLARE(ui_img_play_button_png);    // assets/Play_button.png
LV_IMG_DECLARE(ui_img_big_espresso_png);    // assets/big_espresso.png
LV_IMG_DECLARE(ui_img_big_ristretto_png);    // assets/big_ristretto.png
LV_IMG_DECLARE(ui_img_big_latte_png);    // assets/big_latte.png
LV_IMG_DECLARE(ui_img_arrow_png);    // assets/arrow.png
LV_IMG_DECLARE(ui_img_ble_png);    // assets/ble.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_latte_illustration_png);    // assets/latte_illustration.png
LV_IMG_DECLARE(ui_img_chevron_png);    // assets/chevron.png
LV_IMG_DECLARE(ui_img_266850372);    // assets/chevron-1.png
LV_IMG_DECLARE(ui_img_disabledbean_png);    // assets/disabledbean.png
LV_IMG_DECLARE(ui_img_beans_white_png);    // assets/beans_white.png
LV_IMG_DECLARE(ui_img_cup_png);    // assets/cup.png
LV_IMG_DECLARE(ui_img_cups_png);    // assets/cups.png
LV_IMG_DECLARE(ui_img_coffee_illustration_png);    // assets/Coffee_illustration.png
LV_IMG_DECLARE(ui_img_espresso_png);    // assets/espresso.png
LV_IMG_DECLARE(ui_img_slider_bg_png);    // assets/slider_bg.png
LV_IMG_DECLARE(ui_img_top_png);    // assets/Top.png
LV_IMG_DECLARE(ui_img_parameters_png);    // assets/parameters.png
LV_IMG_DECLARE(ui_img_1726788397);    // assets/parameters-1.png
LV_IMG_DECLARE(ui_img_temp_body_png);    // assets/temp_body.png
LV_IMG_DECLARE(ui_img_temperature_png);    // assets/temperature.png
LV_IMG_DECLARE(ui_img_foam_body_png);    // assets/foam_body.png
LV_IMG_DECLARE(ui_img_foam_png);    // assets/foam.png
LV_IMG_DECLARE(ui_img_done_png);    // assets/done.png
LV_IMG_DECLARE(ui_img_standby_png);    // assets/standby.png
LV_IMG_DECLARE(ui_img_light_png);    // assets/light.png
LV_IMG_DECLARE(ui_img_water_png);    // assets/water.png
LV_IMG_DECLARE(ui_img_clean_png);    // assets/clean.png
LV_IMG_DECLARE(ui_img_taste1_png);    // assets/taste1.png
LV_IMG_DECLARE(ui_img_cup1_png);    // assets/cup1.png
LV_IMG_DECLARE(ui_img_units_png);    // assets/units.png
LV_IMG_DECLARE(ui_img_languages_png);    // assets/languages.png
LV_IMG_DECLARE(ui_img_profile_png);    // assets/profile.png
LV_IMG_DECLARE(ui_img_roller_png);    // assets/roller.png
LV_IMG_DECLARE(ui_img_alert_png);    // assets/alert.png
LV_IMG_DECLARE(ui_img_tank_png);    // assets/tank.png
LV_IMG_DECLARE(ui_img_wave1_png);    // assets/wave1.png
LV_IMG_DECLARE(ui_img_wave_bottom_png);    // assets/wave_bottom.png
LV_IMG_DECLARE(ui_img_done_60_png);    // assets/done_60.png
LV_IMG_DECLARE(ui_img_arrows_png);    // assets/arrows.png
LV_IMG_DECLARE(ui_img_bigbean_png);    // assets/bigbean.png

// FONTS
LV_FONT_DECLARE(ui_font_badge2);
LV_FONT_DECLARE(ui_font_exclamation);
LV_FONT_DECLARE(ui_font_H1_bold);
LV_FONT_DECLARE(ui_font_H2_bold);
LV_FONT_DECLARE(ui_font_H3_bold);
LV_FONT_DECLARE(ui_font_icon);
LV_FONT_DECLARE(ui_font_Min);
LV_FONT_DECLARE(ui_font_P1_bold);
LV_FONT_DECLARE(ui_font_P1_medium);
LV_FONT_DECLARE(ui_font_P2_medium);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
