// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: 3d_printer

#ifndef _3D_PRINTER_UI_H
#define _3D_PRINTER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen_1_Print.h"
#include "screens/ui_Screen_2_Move.h"
#include "screens/ui_Screen_3_Setting.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t *OpaOn_Animation(lv_obj_t *TargetObject, int delay);
extern lv_anim_t *OpaOff_Animation(lv_obj_t *TargetObject, int delay);
extern lv_anim_t *ScreenIn_Animation(lv_obj_t *TargetObject, int delay);
extern lv_anim_t *MenuIn_Animation(lv_obj_t *TargetObject, int delay);
extern lv_anim_t *MenuOut_Animation(lv_obj_t *TargetObject, int delay);
extern lv_anim_t *ScreenOut_Animation(lv_obj_t *TargetObject, int delay);

// EVENTS

extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_3d_printer_bg_png);    // assets/3d_printer_bg.png
LV_IMG_DECLARE(ui_img_icn_wifi_png);    // assets/icn_wifi.png
LV_IMG_DECLARE(ui_img_icn_pc_png);    // assets/icn_pc.png
LV_IMG_DECLARE(ui_img_icn_usb_png);    // assets/icn_usb.png
LV_IMG_DECLARE(ui_img_btn_print_png);    // assets/btn_print.png
LV_IMG_DECLARE(ui_img_btn_move_png);    // assets/btn_move.png
LV_IMG_DECLARE(ui_img_btn_setting_png);    // assets/btn_setting.png
LV_IMG_DECLARE(ui_img_print_view_bg_png);    // assets/print_view_bg.png
LV_IMG_DECLARE(ui_img_print_view_front_png);    // assets/print_view_front.png
LV_IMG_DECLARE(ui_img_icn_time_1_png);    // assets/icn_time_1.png
LV_IMG_DECLARE(ui_img_icn_time_2_png);    // assets/icn_time_2.png
LV_IMG_DECLARE(ui_img_icn_head_png);    // assets/icn_head.png
LV_IMG_DECLARE(ui_img_icn_bed_png);    // assets/icn_bed.png
LV_IMG_DECLARE(ui_img_btn_print_down_png);    // assets/btn_print_down.png
LV_IMG_DECLARE(ui_img_btn_print_top_off_png);    // assets/btn_print_top_off.png
LV_IMG_DECLARE(ui_img_icn_pause_png);    // assets/icn_pause.png
LV_IMG_DECLARE(ui_img_icn_stop_png);    // assets/icn_stop.png
LV_IMG_DECLARE(ui_img_btn_z_botton_png);    // assets/btn_z_botton.png
LV_IMG_DECLARE(ui_img_btn_z_top_png);    // assets/btn_z_top.png
LV_IMG_DECLARE(ui_img_arrow_up_png);    // assets/arrow_up.png
LV_IMG_DECLARE(ui_img_arrow_down_png);    // assets/arrow_down.png
LV_IMG_DECLARE(ui_img_btn_pad_bottom_png);    // assets/btn_pad_bottom.png
LV_IMG_DECLARE(ui_img_btn_pad_top_png);    // assets/btn_pad_top.png
LV_IMG_DECLARE(ui_img_arrow_left_png);    // assets/arrow_left.png
LV_IMG_DECLARE(ui_img_arrow_right_png);    // assets/arrow_right.png
LV_IMG_DECLARE(ui_img_roller_bg_png);    // assets/roller_bg.png
LV_IMG_DECLARE(ui_img_btn_main_off_png);    // assets/btn_main_off.png
LV_IMG_DECLARE(ui_img_btn_main_on_png);    // assets/btn_main_on.png

// FONTS
LV_FONT_DECLARE(ui_font_Small_Font);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
