// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#include "../ui.h"

lv_obj_t * ui_Screen_Customize2 = NULL;
lv_obj_t * ui_Customize2_header_header2 = NULL;
lv_obj_t * ui_Customize2_steps_steps3 = NULL;
lv_obj_t * ui_Customize2_Container_full_content4 = NULL;
lv_obj_t * ui_Customize2_selector_coffee_selector4 = NULL;
lv_obj_t * ui_Customize2_Container_main_parameters4 = NULL;
lv_obj_t * ui_Customize2_Container_content1 = NULL;
lv_obj_t * ui_Customize2_Container_sliders1 = NULL;
lv_obj_t * ui_Customize2_parameter_parameter_slider3 = NULL;
lv_obj_t * ui_Customize2_parameter_parameter_slider4 = NULL;
lv_obj_t * ui_Customize2_Label_num = NULL;
lv_obj_t * ui_Customize2_separator_separator1 = NULL;
lv_obj_t * ui_Customize2_CTA_container_CTA_container4 = NULL;
// event funtions
void ui_event_Screen_Customize2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        top_on_slider_Animation(ui_comp_get_child(ui_Customize2_parameter_parameter_slider3,
                                                  UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 0);
        top_on_slider_Animation(ui_comp_get_child(ui_Customize2_parameter_parameter_slider4,
                                                  UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 0);
        icons_bottom_on_Animation(ui_comp_get_child(ui_Customize2_parameter_parameter_slider3,
                                                    UI_COMP_CONTAINER_PARAMETER_IMAGE_SLIDER_ICON), 0);
        icons_bottom_on_Animation(ui_comp_get_child(ui_Customize2_parameter_parameter_slider4,
                                                    UI_COMP_CONTAINER_PARAMETER_IMAGE_SLIDER_ICON), 0);
        num_bottom_on_Animation(ui_Customize2_Label_num, 0);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        top_off_slider_Animation(ui_comp_get_child(ui_Customize2_parameter_parameter_slider3,
                                                   UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 0);
        top_off_slider_Animation(ui_comp_get_child(ui_Customize2_parameter_parameter_slider4,
                                                   UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 0);
        icons_bottom_off_Animation(ui_comp_get_child(ui_Customize2_parameter_parameter_slider3,
                                                     UI_COMP_CONTAINER_PARAMETER_IMAGE_SLIDER_ICON), 0);
        icons_bottom_off_Animation(ui_comp_get_child(ui_Customize2_parameter_parameter_slider4,
                                                     UI_COMP_CONTAINER_PARAMETER_IMAGE_SLIDER_ICON), 0);
        num_bottom_off_Animation(ui_Customize2_Label_num, 0);
    }
}

void ui_event_Customize2_header_header2_Container_header_panel_Container_left_container_Container_back_btn(
    lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Customize, LV_SCR_LOAD_ANIM_FADE_ON, 0, 300, &ui_Screen_Customize_screen_init);
    }
}

void ui_event_Customize2_header_header2_Container_header_panel_Container_right_container_Container_settings(
    lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen_Settings_screen_init);
    }
}

void ui_event_Customize2_selector_coffee_selector4_Container_selector__Image_left_chevron(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Home_espresso, LV_SCR_LOAD_ANIM_FADE_ON, 0, 600, &ui_Screen_Home_espresso_screen_init);
    }
}

void ui_event_Customize2_selector_coffee_selector4_Container_selector__Image_right_chevron(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Home_ristretto, LV_SCR_LOAD_ANIM_FADE_ON, 0, 600, &ui_Screen_Home_ristretto_screen_init);
    }
}

void ui_event_Customize2_parameter_parameter_slider4_Container_slider_Slider_slider_body(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_comp_get_child(ui_Customize2_selector_coffee_selector4,
                                                    UI_COMP_CONTAINER_SELECTOR_CONTAINER_SELECTOR__CONTAINER_COFFEE_NAME_LABEL_COFFEE_PREFIX), target, "", "x Latte");
        _ui_slider_set_text_value(ui_Customize2_Label_num, target, "x", "");
    }
}

void ui_event_Customize2_CTA_container_CTA_container4_Panel_circle_panel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Brewing, LV_SCR_LOAD_ANIM_FADE_ON, 0, 200, &ui_Screen_Brewing_screen_init);
    }
}

// build funtions

void ui_Screen_Customize2_screen_init(void)
{
    ui_Screen_Customize2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_Customize2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_Customize2, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_Customize2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Screen_Customize2, &ui_img_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Customize2_header_header2 = ui_Container_header_create(ui_Screen_Customize2);
    lv_obj_set_x(ui_Customize2_header_header2, 0);
    lv_obj_set_y(ui_Customize2_header_header2, 0);



    ui_Customize2_steps_steps3 = ui_Container_steps_create(ui_Screen_Customize2);
    lv_obj_set_x(ui_Customize2_steps_steps3, 26);
    lv_obj_set_y(ui_Customize2_steps_steps3, 186);

    lv_obj_set_width(ui_comp_get_child(ui_Customize2_steps_steps3, UI_COMP_CONTAINER_STEPS_PANEL_LEFT_POINT), 16);
    lv_obj_set_height(ui_comp_get_child(ui_Customize2_steps_steps3, UI_COMP_CONTAINER_STEPS_PANEL_LEFT_POINT), 16);
    ui_object_set_themeable_style_property(ui_comp_get_child(ui_Customize2_steps_steps3,
                                                             UI_COMP_CONTAINER_STEPS_PANEL_LEFT_POINT), LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fg_Disabled);
    ui_object_set_themeable_style_property(ui_comp_get_child(ui_Customize2_steps_steps3,
                                                             UI_COMP_CONTAINER_STEPS_PANEL_LEFT_POINT), LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fg_Disabled);

    lv_obj_set_width(ui_comp_get_child(ui_Customize2_steps_steps3, UI_COMP_CONTAINER_STEPS_PANEL_RIGHT_POINT), 20);
    lv_obj_set_height(ui_comp_get_child(ui_Customize2_steps_steps3, UI_COMP_CONTAINER_STEPS_PANEL_RIGHT_POINT), 20);
    ui_object_set_themeable_style_property(ui_comp_get_child(ui_Customize2_steps_steps3,
                                                             UI_COMP_CONTAINER_STEPS_PANEL_RIGHT_POINT), LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(ui_comp_get_child(ui_Customize2_steps_steps3,
                                                             UI_COMP_CONTAINER_STEPS_PANEL_RIGHT_POINT), LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fg_Primary);

    ui_Customize2_Container_full_content4 = lv_obj_create(ui_Screen_Customize2);
    lv_obj_remove_style_all(ui_Customize2_Container_full_content4);
    lv_obj_set_height(ui_Customize2_Container_full_content4, 397);
    lv_obj_set_width(ui_Customize2_Container_full_content4, lv_pct(100));
    lv_obj_set_align(ui_Customize2_Container_full_content4, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Customize2_Container_full_content4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Customize2_Container_full_content4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Customize2_Container_full_content4,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Customize2_Container_full_content4, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Customize2_Container_full_content4, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Customize2_Container_full_content4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Customize2_Container_full_content4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Customize2_Container_full_content4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Customize2_Container_full_content4, 24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Customize2_selector_coffee_selector4 = ui_Container_selector_create(ui_Customize2_Container_full_content4);
    lv_obj_set_x(ui_Customize2_selector_coffee_selector4, 0);
    lv_obj_set_y(ui_Customize2_selector_coffee_selector4, 0);

    lv_obj_add_flag(ui_comp_get_child(ui_Customize2_selector_coffee_selector4,
                                      UI_COMP_CONTAINER_SELECTOR_CONTAINER_SELECTOR__IMAGE_LEFT_CHEVRON), LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_obj_add_flag(ui_comp_get_child(ui_Customize2_selector_coffee_selector4,
                                      UI_COMP_CONTAINER_SELECTOR_CONTAINER_SELECTOR__IMAGE_RIGHT_CHEVRON), LV_OBJ_FLAG_HIDDEN);    /// Flags

    ui_Customize2_Container_main_parameters4 = lv_obj_create(ui_Customize2_Container_full_content4);
    lv_obj_remove_style_all(ui_Customize2_Container_main_parameters4);
    lv_obj_set_height(ui_Customize2_Container_main_parameters4, lv_pct(100));
    lv_obj_set_flex_grow(ui_Customize2_Container_main_parameters4, 3);
    lv_obj_set_align(ui_Customize2_Container_main_parameters4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Customize2_Container_main_parameters4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Customize2_Container_main_parameters4, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Customize2_Container_main_parameters4,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Customize2_Container_main_parameters4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Customize2_Container_main_parameters4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Customize2_Container_main_parameters4, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Customize2_Container_main_parameters4, 44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Customize2_Container_content1 = lv_obj_create(ui_Customize2_Container_main_parameters4);
    lv_obj_remove_style_all(ui_Customize2_Container_content1);
    lv_obj_set_width(ui_Customize2_Container_content1, lv_pct(100));
    lv_obj_set_height(ui_Customize2_Container_content1, lv_pct(100));
    lv_obj_set_align(ui_Customize2_Container_content1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Customize2_Container_content1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Customize2_Container_content1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Customize2_Container_content1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Customize2_Container_content1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Customize2_Container_content1, 33, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Customize2_Container_content1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Customize2_Container_content1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Customize2_Container_content1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Customize2_Container_content1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Customize2_Container_sliders1 = lv_obj_create(ui_Customize2_Container_content1);
    lv_obj_remove_style_all(ui_Customize2_Container_sliders1);
    lv_obj_set_height(ui_Customize2_Container_sliders1, lv_pct(100));
    lv_obj_set_flex_grow(ui_Customize2_Container_sliders1, 1);
    lv_obj_set_align(ui_Customize2_Container_sliders1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Customize2_Container_sliders1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Customize2_Container_sliders1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Customize2_Container_sliders1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Customize2_Container_sliders1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Customize2_Container_sliders1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Customize2_Container_sliders1, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Customize2_Container_sliders1, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Customize2_Container_sliders1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Customize2_Container_sliders1, 41, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Customize2_parameter_parameter_slider3 = ui_Container_parameter_create(ui_Customize2_Container_sliders1);
    lv_obj_set_x(ui_Customize2_parameter_parameter_slider3, 0);
    lv_obj_set_y(ui_Customize2_parameter_parameter_slider3, 0);

    lv_slider_set_range(ui_comp_get_child(ui_Customize2_parameter_parameter_slider3,
                                          UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 1, 4);
    lv_slider_set_value(ui_comp_get_child(ui_Customize2_parameter_parameter_slider3,
                                          UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 4, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_comp_get_child(ui_Customize2_parameter_parameter_slider3,
                                            UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY)) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
                                                    ui_comp_get_child(ui_Customize2_parameter_parameter_slider3,
                                                                      UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 0, LV_ANIM_OFF);

    lv_obj_set_style_radius(ui_comp_get_child(ui_Customize2_parameter_parameter_slider3,
                                              UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_comp_get_child(ui_Customize2_parameter_parameter_slider3,
                                                UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), lv_color_hex(0x353B40),
                              LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_Customize2_parameter_parameter_slider3,
                                              UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_comp_get_child(ui_Customize2_parameter_parameter_slider3,
                                                    UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), &ui_img_foam_body_png,
                                  LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_comp_get_child(ui_Customize2_parameter_parameter_slider3,
                                                             UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), LV_PART_KNOB | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_fg_Disabled);
    ui_object_set_themeable_style_property(ui_comp_get_child(ui_Customize2_parameter_parameter_slider3,
                                                             UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), LV_PART_KNOB | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_fg_Disabled);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    lv_image_set_src(ui_comp_get_child(ui_Customize2_parameter_parameter_slider3,
                                       UI_COMP_CONTAINER_PARAMETER_IMAGE_SLIDER_ICON), &ui_img_foam_png);

    ui_Customize2_parameter_parameter_slider4 = ui_Container_parameter_create(ui_Customize2_Container_sliders1);
    lv_obj_set_x(ui_Customize2_parameter_parameter_slider4, 0);
    lv_obj_set_y(ui_Customize2_parameter_parameter_slider4, 0);

    lv_slider_set_range(ui_comp_get_child(ui_Customize2_parameter_parameter_slider4,
                                          UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 1, 2);
    lv_slider_set_value(ui_comp_get_child(ui_Customize2_parameter_parameter_slider4,
                                          UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 1, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_comp_get_child(ui_Customize2_parameter_parameter_slider4,
                                            UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY)) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
                                                    ui_comp_get_child(ui_Customize2_parameter_parameter_slider4,
                                                                      UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 0, LV_ANIM_OFF);

    ui_object_set_themeable_style_property(ui_comp_get_child(ui_Customize2_parameter_parameter_slider4,
                                                             UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(ui_comp_get_child(ui_Customize2_parameter_parameter_slider4,
                                                             UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fg_Primary);

    ui_object_set_themeable_style_property(ui_comp_get_child(ui_Customize2_parameter_parameter_slider4,
                                                             UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), LV_PART_KNOB | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_fg_Disabled);
    ui_object_set_themeable_style_property(ui_comp_get_child(ui_Customize2_parameter_parameter_slider4,
                                                             UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), LV_PART_KNOB | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_fg_Disabled);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    ui_Customize2_Label_num = lv_label_create(ui_Customize2_parameter_parameter_slider4);
    lv_obj_set_width(ui_Customize2_Label_num, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Customize2_Label_num, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Customize2_Label_num, 17);
    lv_obj_set_y(ui_Customize2_Label_num, 105);
    lv_obj_set_align(ui_Customize2_Label_num, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Customize2_Label_num, "x1");
    lv_obj_add_flag(ui_Customize2_Label_num, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    ui_object_set_themeable_style_property(ui_Customize2_Label_num, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(ui_Customize2_Label_num, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_text_font(ui_Customize2_Label_num, &ui_font_icon, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_Customize2_Label_num, 1);
    lv_image_set_src(ui_comp_get_child(ui_Customize2_parameter_parameter_slider4,
                                       UI_COMP_CONTAINER_PARAMETER_IMAGE_SLIDER_ICON), &ui_img_parameters_png);

    ui_Customize2_separator_separator1 = ui_Container_separator_create(ui_Customize2_Container_main_parameters4);
    lv_obj_set_x(ui_Customize2_separator_separator1, 0);
    lv_obj_set_y(ui_Customize2_separator_separator1, 79);

    lv_obj_set_width(ui_comp_get_child(ui_Customize2_separator_separator1, UI_COMP_CONTAINER_SEPARATOR_PANEL_TOP_PANEL), 1);
    lv_obj_set_height(ui_comp_get_child(ui_Customize2_separator_separator1, UI_COMP_CONTAINER_SEPARATOR_PANEL_TOP_PANEL),
                      164);

    lv_obj_set_width(ui_comp_get_child(ui_Customize2_separator_separator1, UI_COMP_CONTAINER_SEPARATOR_PANEL_BOTTOM_PANEL),
                     1);
    lv_obj_set_height(ui_comp_get_child(ui_Customize2_separator_separator1, UI_COMP_CONTAINER_SEPARATOR_PANEL_BOTTOM_PANEL),
                      164);

    ui_Customize2_CTA_container_CTA_container4 = ui_Container_CTA_container_create(ui_Customize2_Container_full_content4);
    lv_obj_set_x(ui_Customize2_CTA_container_CTA_container4, 0);
    lv_obj_set_y(ui_Customize2_CTA_container_CTA_container4, 0);

    lv_label_set_text(ui_comp_get_child(ui_Customize2_CTA_container_CTA_container4,
                                        UI_COMP_CONTAINER_CTA_CONTAINER_LABEL_EXTRACT), "Start");

    lv_obj_add_event_cb(ui_comp_get_child(ui_Customize2_header_header2,
                                          UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_LEFT_CONTAINER_CONTAINER_BACK_BTN),
                        ui_event_Customize2_header_header2_Container_header_panel_Container_left_container_Container_back_btn, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Customize2_header_header2,
                                          UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_SETTINGS),
                        ui_event_Customize2_header_header2_Container_header_panel_Container_right_container_Container_settings, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Customize2_selector_coffee_selector4,
                                          UI_COMP_CONTAINER_SELECTOR_CONTAINER_SELECTOR__IMAGE_LEFT_CHEVRON),
                        ui_event_Customize2_selector_coffee_selector4_Container_selector__Image_left_chevron, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Customize2_selector_coffee_selector4,
                                          UI_COMP_CONTAINER_SELECTOR_CONTAINER_SELECTOR__IMAGE_RIGHT_CHEVRON),
                        ui_event_Customize2_selector_coffee_selector4_Container_selector__Image_right_chevron, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Customize2_parameter_parameter_slider4,
                                          UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY),
                        ui_event_Customize2_parameter_parameter_slider4_Container_slider_Slider_slider_body, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Customize2_CTA_container_CTA_container4,
                                          UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL),
                        ui_event_Customize2_CTA_container_CTA_container4_Panel_circle_panel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen_Customize2, ui_event_Screen_Customize2, LV_EVENT_ALL, NULL);

}

void ui_Screen_Customize2_screen_destroy(void)
{
    if(ui_Screen_Customize2) lv_obj_del(ui_Screen_Customize2);

    // NULL screen variables
    ui_Screen_Customize2 = NULL;
    ui_Customize2_header_header2 = NULL;
    ui_Customize2_steps_steps3 = NULL;
    ui_Customize2_Container_full_content4 = NULL;
    ui_Customize2_selector_coffee_selector4 = NULL;
    ui_Customize2_Container_main_parameters4 = NULL;
    ui_Customize2_Container_content1 = NULL;
    ui_Customize2_Container_sliders1 = NULL;
    ui_Customize2_parameter_parameter_slider3 = NULL;
    ui_Customize2_parameter_parameter_slider4 = NULL;
    ui_Customize2_Label_num = NULL;
    ui_Customize2_separator_separator1 = NULL;
    ui_Customize2_CTA_container_CTA_container4 = NULL;

}
