// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#ifndef UI_SCREEN_SPLASH_SCREEN_H
#define UI_SCREEN_SPLASH_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_Splash_screen
extern void ui_Screen_Splash_screen_screen_init(void);
extern void ui_Screen_Splash_screen_screen_destroy(void);
extern void ui_event_Screen_Splash_screen(lv_event_t * e);
extern lv_obj_t * ui_Screen_Splash_screen;
extern lv_obj_t * ui_Splash_screen_Label_caffee;
extern lv_obj_t * ui_Splash_screen_Label_example;
extern lv_obj_t * ui_Splash_screen_Label_squareline;
extern lv_obj_t * ui_Splash_screen_Image_shape;
extern lv_obj_t * ui_Splash_screen_CTA_container_CTA_container9;
extern void ui_event_Splash_screen_CTA_container_CTA_container9_Panel_circle_panel(lv_event_t * e);
extern lv_obj_t * ui_Splash_screen_Image_big_espresso;
extern lv_obj_t * ui_Splash_screen_Image_big_ristretto;
extern lv_obj_t * ui_Splash_screen_Image_big_latte;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

