// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#ifndef UI_SCREEN_ADD_WATER_H
#define UI_SCREEN_ADD_WATER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_Add_water
extern void ui_Screen_Add_water_screen_init(void);
extern void ui_Screen_Add_water_screen_destroy(void);
extern void ui_event_Screen_Add_water(lv_event_t * e);
extern lv_obj_t * ui_Screen_Add_water;
extern lv_obj_t * ui_Add_water_header_header9;
extern lv_obj_t * ui_Add_water_Container_middle_content;
extern lv_obj_t * ui_Add_water_Container_exclamation_container;
extern lv_obj_t * ui_Add_water_CTA_container_CTA_container8;
extern lv_obj_t * ui_Add_water_Container_mid_container;
extern lv_obj_t * ui_Add_water_Image_tank;
extern lv_obj_t * ui_Add_water_Container_waves_;
extern lv_obj_t * ui_Add_water_Image_wave_bg;
extern lv_obj_t * ui_Add_water_Image_wave_fg;
extern lv_obj_t * ui_Add_water_Image_wave_bottom;
extern lv_obj_t * ui_Add_water_Label_min;
extern lv_obj_t * ui_Add_water_Container_Done_container;
extern lv_obj_t * ui_Add_water_CTA_container_CTA_container6;
extern void ui_event_Add_water_CTA_container_CTA_container6_Panel_circle_panel(lv_event_t * e);
extern lv_obj_t * ui_Add_water_Container_footer;
extern lv_obj_t * ui_Add_water_Label_refill;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

