// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#ifndef UI_SCREEN_READY_H
#define UI_SCREEN_READY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_Ready
extern void ui_Screen_Ready_screen_init(void);
extern void ui_Screen_Ready_screen_destroy(void);
extern void ui_event_Screen_Ready(lv_event_t * e);
extern lv_obj_t * ui_Screen_Ready;
extern lv_obj_t * ui_Ready_Label_enjoy;
extern lv_obj_t * ui_Ready_ready_button_ready_button1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

