// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#ifndef UI_SCREEN_ADD_COFFEE_H
#define UI_SCREEN_ADD_COFFEE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_Add_coffee
extern void ui_Screen_Add_coffee_screen_init(void);
extern void ui_Screen_Add_coffee_screen_destroy(void);
extern void ui_event_Screen_Add_coffee(lv_event_t * e);
extern lv_obj_t * ui_Screen_Add_coffee;
extern lv_obj_t * ui_Add_coffee_header_header10;
extern lv_obj_t * ui_Add_coffee_Container_mid_content;
extern lv_obj_t * ui_Add_coffee_Container_exclamation_container;
extern lv_obj_t * ui_Add_coffee_CTA_container_CTA_container5;
extern lv_obj_t * ui_Add_coffee_Container_mid_container;
extern lv_obj_t * ui_Add_coffee_Image_arrows;
extern lv_obj_t * ui_Add_coffee_Image_big_bean;
extern lv_obj_t * ui_Add_coffee_Container_Done_container;
extern lv_obj_t * ui_Add_coffee_CTA_container_CTA_container11;
extern void ui_event_Add_coffee_CTA_container_CTA_container11_Panel_circle_panel(lv_event_t * e);
extern lv_obj_t * ui_Add_coffee_Container_footer;
extern lv_obj_t * ui_Add_coffee_Label_refill1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

