// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#include "../ui.h"

lv_obj_t * ui_Screen_Brewing_Done = NULL;
lv_obj_t * ui_Brewing_Done_header_header6 = NULL;
lv_obj_t * ui_Brewing_Done_Label_enjoy = NULL;
lv_obj_t * ui_Brewing_Done_Container_full_content6 = NULL;
lv_obj_t * ui_Brewing_Done_ready_button_ready_button = NULL;
// event funtions
void ui_event_Screen_Brewing_Done(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        enjoy_bottom_off_Animation(ui_Brewing_Done_Label_enjoy, 1500);
        enjoybtn_top_off_Animation(ui_Brewing_Done_ready_button_ready_button, 1500);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_Screen_Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 2000, &ui_Screen_Home_screen_init);
        enjoy_bottom_on_Animation(ui_Brewing_Done_Label_enjoy, 0);
        enjoybtn_top_on_Animation(ui_Brewing_Done_ready_button_ready_button, 0);
    }
}

// build funtions

void ui_Screen_Brewing_Done_screen_init(void)
{
    ui_Screen_Brewing_Done = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_Brewing_Done, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Screen_Brewing_Done, &ui_img_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Screen_Brewing_Done, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Brewing_Done_header_header6 = ui_Container_header_create(ui_Screen_Brewing_Done);
    lv_obj_set_x(ui_Brewing_Done_header_header6, 0);
    lv_obj_set_y(ui_Brewing_Done_header_header6, 0);

    lv_obj_add_state(ui_comp_get_child(ui_Brewing_Done_header_header6,
                                       UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_LEFT_CONTAINER_CONTAINER_BACK_BTN),
                     LV_STATE_DISABLED);      /// States
    lv_obj_remove_flag(ui_comp_get_child(ui_Brewing_Done_header_header6,
                                         UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_LEFT_CONTAINER_CONTAINER_BACK_BTN),
                       LV_OBJ_FLAG_CLICKABLE);    /// Flags

    lv_label_set_text(ui_comp_get_child(ui_Brewing_Done_header_header6,
                                        UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_LABEL_TITLE), "Brewing");

    lv_obj_remove_flag(ui_comp_get_child(ui_Brewing_Done_header_header6,
                                         UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_STATUS_ICONS_CONTAINER_ICONS_ROW_IMAGE_WIFI),
                       LV_OBJ_FLAG_CLICKABLE);     /// Flags

    lv_obj_add_state(ui_comp_get_child(ui_Brewing_Done_header_header6,
                                       UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_SETTINGS),
                     LV_STATE_DISABLED);      /// States
    lv_obj_remove_flag(ui_comp_get_child(ui_Brewing_Done_header_header6,
                                         UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_SETTINGS),
                       LV_OBJ_FLAG_CLICKABLE);    /// Flags

    ui_Brewing_Done_Label_enjoy = lv_label_create(ui_Screen_Brewing_Done);
    lv_obj_set_width(ui_Brewing_Done_Label_enjoy, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Brewing_Done_Label_enjoy, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Brewing_Done_Label_enjoy, 0);
    lv_obj_set_y(ui_Brewing_Done_Label_enjoy, 140);
    lv_obj_set_align(ui_Brewing_Done_Label_enjoy, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Brewing_Done_Label_enjoy, "Enjoy your drink!");
    ui_object_set_themeable_style_property(ui_Brewing_Done_Label_enjoy, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(ui_Brewing_Done_Label_enjoy, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_text_font(ui_Brewing_Done_Label_enjoy, &ui_font_H3_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Brewing_Done_Container_full_content6 = lv_obj_create(ui_Screen_Brewing_Done);
    lv_obj_remove_style_all(ui_Brewing_Done_Container_full_content6);
    lv_obj_set_height(ui_Brewing_Done_Container_full_content6, 397);
    lv_obj_set_width(ui_Brewing_Done_Container_full_content6, lv_pct(100));
    lv_obj_set_align(ui_Brewing_Done_Container_full_content6, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_Brewing_Done_Container_full_content6,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Brewing_Done_Container_full_content6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Brewing_Done_Container_full_content6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Brewing_Done_Container_full_content6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Brewing_Done_Container_full_content6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Brewing_Done_Container_full_content6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Brewing_Done_Container_full_content6, 48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Brewing_Done_ready_button_ready_button = ui_Panel_ready_button_create(ui_Brewing_Done_Container_full_content6);
    lv_obj_set_x(ui_Brewing_Done_ready_button_ready_button, 0);
    lv_obj_set_y(ui_Brewing_Done_ready_button_ready_button, -30);

    lv_obj_add_event_cb(ui_Screen_Brewing_Done, ui_event_Screen_Brewing_Done, LV_EVENT_ALL, NULL);

}

void ui_Screen_Brewing_Done_screen_destroy(void)
{
    if(ui_Screen_Brewing_Done) lv_obj_del(ui_Screen_Brewing_Done);

    // NULL screen variables
    ui_Screen_Brewing_Done = NULL;
    ui_Brewing_Done_header_header6 = NULL;
    ui_Brewing_Done_Label_enjoy = NULL;
    ui_Brewing_Done_Container_full_content6 = NULL;
    ui_Brewing_Done_ready_button_ready_button = NULL;

}
