// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"


// IMAGE DATA: assets/2.png
lv_img_dsc_t ui_img_2_png =
{
    .header.w = 114,
    .header.h = 108,
    .header.cf = LV_COLOR_FORMAT_RGB565A8,
};

void ui_img_2_png_load()
{
    ui_img_2_png.data = UI_LOAD_IMAGE("0:1.bin", 36940);
    ui_img_2_png.data_size = 36940;
}
