// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: ebike_demo

#ifndef _EBIKE_DEMO_UI_COMP_HOOK_H
#define _EBIKE_DEMO_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_Dropdown_create_hook(lv_obj_t * comp);
void ui_comp_Roller_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
