// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: ebike_demo

#include "../ui.h"

// COMPONENT Dropdown

lv_obj_t * ui_Dropdown_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Dropdown;
    cui_Dropdown = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Dropdown, 150);
    lv_obj_set_height(cui_Dropdown, 64);
    lv_obj_set_x(cui_Dropdown, 0);
    lv_obj_set_y(cui_Dropdown, 23);
    lv_obj_set_align(cui_Dropdown, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Dropdown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Dropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Dropdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Dropdown, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Dropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Dropdown, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_Dropdown, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_Dropdown, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Dropdown, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Dropdown, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Dropdown, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label_dropdown;
    cui_Label_dropdown = lv_label_create(cui_Dropdown);
    lv_obj_set_width(cui_Label_dropdown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label_dropdown, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(cui_Label_dropdown, "Bike mode");
    lv_obj_set_style_text_color(cui_Label_dropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label_dropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label_dropdown, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Dropdown2;
    cui_Dropdown2 = lv_dropdown_create(cui_Dropdown);
    lv_dropdown_set_options(cui_Dropdown2, "Echo\nCity\nMontain\nRace");
    lv_obj_set_height(cui_Dropdown2, 30);
    lv_obj_set_width(cui_Dropdown2, lv_pct(100));
    lv_obj_set_align(cui_Dropdown2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(cui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(cui_Dropdown2, lv_color_hex(0xFFFAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Dropdown2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(cui_Dropdown2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Dropdown2, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_Dropdown2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Dropdown2, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Dropdown2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_Dropdown2, lv_color_hex(0x181818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(cui_Dropdown2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Dropdown2, lv_color_hex(0x7B8183), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Dropdown2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Dropdown2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_Dropdown2, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_Dropdown2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Dropdown2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Dropdown2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Dropdown2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(cui_Dropdown2, LV_TEXT_ALIGN_CENTER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Dropdown2, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(cui_Dropdown2), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(cui_Dropdown2), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(cui_Dropdown2), &ui_font_Medium,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(lv_dropdown_get_list(cui_Dropdown2), 6,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(cui_Dropdown2), lv_color_hex(0x121212),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(cui_Dropdown2), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(lv_dropdown_get_list(cui_Dropdown2), true,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(lv_dropdown_get_list(cui_Dropdown2), 10,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(lv_dropdown_get_list(cui_Dropdown2), 10,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(lv_dropdown_get_list(cui_Dropdown2), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(lv_dropdown_get_list(cui_Dropdown2), 10,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(cui_Dropdown2), lv_color_hex(0xFFFAE6),
                                LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(cui_Dropdown2), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(cui_Dropdown2), lv_color_hex(0xD56920),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(cui_Dropdown2), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(cui_Dropdown2), lv_color_hex(0x203439),
                              LV_PART_SELECTED | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(cui_Dropdown2), 255,  LV_PART_SELECTED | LV_STATE_CHECKED);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_DROPDOWN_NUM);
    children[UI_COMP_DROPDOWN_DROPDOWN] = cui_Dropdown;
    children[UI_COMP_DROPDOWN_LABEL_DROPDOWN] = cui_Label_dropdown;
    children[UI_COMP_DROPDOWN_DROPDOWN2] = cui_Dropdown2;
    lv_obj_add_event_cb(cui_Dropdown, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Dropdown, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Dropdown_create_hook(cui_Dropdown);
    return cui_Dropdown;
}

