// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: Medical

#ifndef _MEDICAL_UI_H
#define _MEDICAL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void HistoryAnim_Animation(lv_obj_t *TargetObject, int delay);
void HistoryAnimOff_Animation(lv_obj_t *TargetObject, int delay);
void HeartAnim_Animation(lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Medical_Screen
void ui_Medical_Screen_screen_init(void);
extern lv_obj_t *ui_Medical_Screen;
extern lv_obj_t *ui_Panel_History;
extern lv_obj_t *ui_Label_History;
extern lv_obj_t *ui_Label_YBP;
extern lv_obj_t *ui_Panel_History_Content;
extern lv_obj_t *ui_Panel_Today;
extern lv_obj_t *ui_Label_Today;
extern lv_obj_t *ui_Panel_Today_Content_1;
extern lv_obj_t *ui_Label_List_1;
extern lv_obj_t *ui_Label_Date_1;
extern lv_obj_t *ui_Label_List_1_copy;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Panel_Today_Content_2;
extern lv_obj_t *ui_Label_List_2;
extern lv_obj_t *ui_Label_Date_2;
extern lv_obj_t *ui_Label_List_Pul_2;
extern lv_obj_t *ui_IMG_Heart_Small_1;
extern lv_obj_t *ui_Panel_Today_Content_3;
extern lv_obj_t *ui_Label_List_3;
extern lv_obj_t *ui_Label_Date_3;
extern lv_obj_t *ui_Label_List_Pul_3;
extern lv_obj_t *ui_IMG_Heart_Small_2;
extern lv_obj_t *ui_Panel_Yesterday;
extern lv_obj_t *ui_Label_Yesterday;
extern lv_obj_t *ui_Panel_Today_Content_5;
extern lv_obj_t *ui_Label_List_5;
extern lv_obj_t *ui_Label_Date_5;
extern lv_obj_t *ui_Label_List_Pul_5;
extern lv_obj_t *ui_IMG_Heart_Small_5;
extern lv_obj_t *ui_Panel_Today_Content_6;
extern lv_obj_t *ui_Label_List_6;
extern lv_obj_t *ui_Label_Date_6;
extern lv_obj_t *ui_Label_List_Pul_6;
extern lv_obj_t *ui_IMG_Heart_Small_6;
extern lv_obj_t *ui_Panel_Today_Content_7;
extern lv_obj_t *ui_Label_List_7;
extern lv_obj_t *ui_Label_Date_7;
extern lv_obj_t *ui_Label_List_Pul_7;
extern lv_obj_t *ui_IMG_Heart_Small_7;
void ui_event_Panel_S1(lv_event_t *e);
extern lv_obj_t *ui_Panel_S1;
void ui_event_BTN_History(lv_event_t *e);
extern lv_obj_t *ui_BTN_History;
extern lv_obj_t *ui_Label_Date;
extern lv_obj_t *ui_Label_Hour;
extern lv_obj_t *ui_IMG_Battery;
extern lv_obj_t *ui_IMG_Bluetooth;
extern lv_obj_t *ui_Label_Battey;
extern lv_obj_t *ui_Panel_Content;
extern lv_obj_t *ui_Slider1;
extern lv_obj_t *ui_Line_1;
extern lv_obj_t *ui_Line_2;
extern lv_obj_t *ui_Line_3;
extern lv_obj_t *ui_Line_4;
extern lv_obj_t *ui_IMG_Line_1;
extern lv_obj_t *ui_IMG_Line_2;
extern lv_obj_t *ui_IMG_Line_3;
extern lv_obj_t *ui_Number_SYS;
extern lv_obj_t *ui_Number_DIA;
extern lv_obj_t *ui_Number_PUL;
extern lv_obj_t *ui_Label_SYS;
extern lv_obj_t *ui_Label_mmHg_1;
extern lv_obj_t *ui_Label_DIA;
extern lv_obj_t *ui_Label_mmHg_2;
extern lv_obj_t *ui_Label_PUL;
extern lv_obj_t *ui_Label_mmHg_3;
extern lv_obj_t *ui_IMG_Heart;
extern lv_obj_t *ui_Panel_Bottom;
extern lv_obj_t *ui_IMG_BTN_Bg;
void ui_event_BTN_Power(lv_event_t *e);
extern lv_obj_t *ui_BTN_Power;
extern lv_obj_t *ui_Switch_Sound;
extern lv_obj_t *ui_Label_Sound;
void ui_event_Switch_Bluetooth(lv_event_t *e);
extern lv_obj_t *ui_Switch_Bluetooth;
extern lv_obj_t *ui_Label_Bluetooth;
void ui_event_initialactions0(lv_event_t *e);
extern lv_obj_t *ui_initialactions0;


LV_IMG_DECLARE(ui_img_img_heart_small_png);    // assets/img_heart_small.png
LV_IMG_DECLARE(ui_img_icn_history_png);    // assets/icn_history.png
LV_IMG_DECLARE(ui_img_icn_battery_png);    // assets/icn_battery.png
LV_IMG_DECLARE(ui_img_icn_bluetooth_png);    // assets/icn_bluetooth.png
LV_IMG_DECLARE(ui_img_img_slider_png);    // assets/img_slider.png
LV_IMG_DECLARE(ui_img_img_line_png);    // assets/img_line.png
LV_IMG_DECLARE(ui_img_img_heart_big_png);    // assets/img_heart_big.png
LV_IMG_DECLARE(ui_img_img_btn_bg_png);    // assets/img_btn_bg.png
LV_IMG_DECLARE(ui_img_img_btn_off_png);    // assets/img_btn_off.png
LV_IMG_DECLARE(ui_img_img_btn_on_png);    // assets/img_btn_on.png
LV_IMG_DECLARE(ui_img_img_switch_bg_png);    // assets/img_switch_bg.png



LV_FONT_DECLARE(ui_font_Big_Number);
LV_FONT_DECLARE(ui_font_Bold_Font);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
