// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: 3d_printer

#ifndef UI_SCREEN_1_PRINT_H
#define UI_SCREEN_1_PRINT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_1_Print
extern void ui_Screen_1_Print_screen_init(void);
extern void ui_Screen_1_Print_screen_destroy(void);
extern lv_obj_t *ui_Screen_1_Print;
extern lv_obj_t *ui_Background;
extern lv_obj_t *ui_Panel_Header;
extern lv_obj_t *ui_Label_Header;
extern lv_obj_t *ui_IMG_Wifi;
extern lv_obj_t *ui_IMG_PC;
extern lv_obj_t *ui_IMG_USB;
extern lv_obj_t *ui_BTN_Menu_Print_S1;
extern void ui_event_BTN_Menu_Move_S1(lv_event_t *e);
extern lv_obj_t *ui_BTN_Menu_Move_S1;
extern void ui_event_BTN_Menu_Setting_S1(lv_event_t *e);
extern lv_obj_t *ui_BTN_Menu_Setting_S1;
extern lv_obj_t *ui_S1_Content_Panel;
extern void ui_event_Slider_Print_View(lv_event_t *e);
extern lv_obj_t *ui_Slider_Print_View;
extern lv_obj_t *ui_Number_Print;
extern lv_obj_t *ui_Display_Time_S1;
extern lv_obj_t *ui_DT1;
extern lv_obj_t *ui_Label_Printing_Time_1;
extern lv_obj_t *ui_IMG_Tine_1;
extern lv_obj_t *ui_Label_Time_1;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_DT2;
extern lv_obj_t *ui_Label_Printing_Time_2;
extern lv_obj_t *ui_IMG_Tine_2;
extern lv_obj_t *ui_Label_Time_2;
extern lv_obj_t *ui_Display_Heat_S1;
extern lv_obj_t *ui_DT3;
extern lv_obj_t *ui_Label_Printing_Head_Temp;
extern lv_obj_t *ui_IMG_Head;
extern lv_obj_t *ui_Label_Head_Temp;
extern lv_obj_t *ui_Label_Printing_Head_Temp_2;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_DT3_copy;
extern lv_obj_t *ui_Label_Printing_Bed_Temp;
extern lv_obj_t *ui_IMG_Head1;
extern lv_obj_t *ui_Label_Bed_Temp;
extern lv_obj_t *ui_Label_Printing_Bed_Temp1;
extern lv_obj_t *ui_Panel_Buttons_S1;
extern lv_obj_t *ui_BTN_Pause;
extern lv_obj_t *ui_BTN_Pause_Top;
extern lv_obj_t *ui_Image_Pause;
extern lv_obj_t *ui_BTN_Cancel;
extern void ui_event_BTN_Cancel_Top(lv_event_t *e);
extern lv_obj_t *ui_BTN_Cancel_Top;
extern lv_obj_t *ui_Image_Cancel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

