// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#include "../ui.h"

lv_obj_t * ui_Screen_Customize = NULL;
lv_obj_t * ui_Customize_header_header = NULL;
lv_obj_t * ui_Customize_steps_steps = NULL;
lv_obj_t * ui_Customize_Container_full_content1 = NULL;
lv_obj_t * ui_Customize_Panel_length_badge = NULL;
lv_obj_t * ui_Customize_Label_coffee_ml = NULL;
lv_obj_t * ui_Customize_Panel_length_badge2 = NULL;
lv_obj_t * ui_Customize_Label_milk_ml = NULL;
lv_obj_t * ui_Customize_selector_coffee_selector1 = NULL;
lv_obj_t * ui_Customize_Container_main_parameters1 = NULL;
lv_obj_t * ui_Customize_Container_content = NULL;
lv_obj_t * ui_Customize_Container_sliders = NULL;
lv_obj_t * ui_Customize_parameter_parameter_slider = NULL;
lv_obj_t * ui_Customize_parameter_parameter_slider1 = NULL;
lv_obj_t * ui_Customize_parameter_parameter_slider2 = NULL;
lv_obj_t * ui_Customize_separator_separator4 = NULL;
lv_obj_t * ui_Customize_CTA_container_CTA_container1 = NULL;
// event funtions
void ui_event_Screen_Customize(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        top_on_slider_Animation(ui_comp_get_child(ui_Customize_parameter_parameter_slider,
                                                  UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 0);
        top_on_slider_Animation(ui_comp_get_child(ui_Customize_parameter_parameter_slider1,
                                                  UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 0);
        top_on_slider_Animation(ui_comp_get_child(ui_Customize_parameter_parameter_slider2,
                                                  UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 0);
        icons_bottom_on_Animation(ui_comp_get_child(ui_Customize_parameter_parameter_slider2,
                                                    UI_COMP_CONTAINER_PARAMETER_IMAGE_SLIDER_ICON), 0);
        icons_bottom_on_Animation(ui_comp_get_child(ui_Customize_parameter_parameter_slider1,
                                                    UI_COMP_CONTAINER_PARAMETER_IMAGE_SLIDER_ICON), 0);
        icons_bottom_on_Animation(ui_comp_get_child(ui_Customize_parameter_parameter_slider,
                                                    UI_COMP_CONTAINER_PARAMETER_IMAGE_SLIDER_ICON), 0);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        top_off_slider_Animation(ui_comp_get_child(ui_Customize_parameter_parameter_slider,
                                                   UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 0);
        top_off_slider_Animation(ui_comp_get_child(ui_Customize_parameter_parameter_slider1,
                                                   UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 0);
        top_off_slider_Animation(ui_comp_get_child(ui_Customize_parameter_parameter_slider2,
                                                   UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 0);
        icons_bottom_off_Animation(ui_comp_get_child(ui_Customize_parameter_parameter_slider,
                                                     UI_COMP_CONTAINER_PARAMETER_IMAGE_SLIDER_ICON), 0);
        icons_bottom_off_Animation(ui_comp_get_child(ui_Customize_parameter_parameter_slider1,
                                                     UI_COMP_CONTAINER_PARAMETER_IMAGE_SLIDER_ICON), 0);
        icons_bottom_off_Animation(ui_comp_get_child(ui_Customize_parameter_parameter_slider2,
                                                     UI_COMP_CONTAINER_PARAMETER_IMAGE_SLIDER_ICON), 0);
    }
}

void ui_event_Customize_header_header_Container_header_panel_Container_left_container_Container_back_btn(
    lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 300, &ui_Screen_Home_screen_init);
    }
}

void ui_event_Customize_header_header_Container_header_panel_Container_right_container_Container_settings(
    lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen_Settings_screen_init);
    }
}

void ui_event_Customize_selector_coffee_selector1_Container_selector__Image_left_chevron(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Home_espresso, LV_SCR_LOAD_ANIM_FADE_ON, 0, 600, &ui_Screen_Home_espresso_screen_init);
    }
}

void ui_event_Customize_selector_coffee_selector1_Container_selector__Image_right_chevron(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Home_ristretto, LV_SCR_LOAD_ANIM_FADE_ON, 0, 600, &ui_Screen_Home_ristretto_screen_init);
    }
}

void ui_event_Customize_parameter_parameter_slider_Container_slider_Slider_slider_body(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_Customize_Label_coffee_ml, target, "", "ml");
    }
    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Customize_Panel_length_badge, LV_STATE_PRESSED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_state_modify(ui_Customize_Panel_length_badge, LV_STATE_PRESSED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Customize_parameter_parameter_slider1_Container_slider_Slider_slider_body(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Customize_Label_milk_ml, target, "", "ml");
    }
    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Customize_Panel_length_badge2, LV_STATE_PRESSED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_state_modify(ui_Customize_Panel_length_badge2, LV_STATE_PRESSED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Customize_CTA_container_CTA_container1_Panel_circle_panel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Customize2, LV_SCR_LOAD_ANIM_FADE_ON, 0, 200, &ui_Screen_Customize2_screen_init);
    }
}

// build funtions

void ui_Screen_Customize_screen_init(void)
{
    ui_Screen_Customize = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_Customize, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_Customize, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_Customize, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Screen_Customize, &ui_img_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Customize_header_header = ui_Container_header_create(ui_Screen_Customize);
    lv_obj_set_x(ui_Customize_header_header, 0);
    lv_obj_set_y(ui_Customize_header_header, 0);



    ui_Customize_steps_steps = ui_Container_steps_create(ui_Screen_Customize);
    lv_obj_set_x(ui_Customize_steps_steps, 26);
    lv_obj_set_y(ui_Customize_steps_steps, 186);

    ui_Customize_Container_full_content1 = lv_obj_create(ui_Screen_Customize);
    lv_obj_remove_style_all(ui_Customize_Container_full_content1);
    lv_obj_set_height(ui_Customize_Container_full_content1, 397);
    lv_obj_set_width(ui_Customize_Container_full_content1, lv_pct(100));
    lv_obj_set_align(ui_Customize_Container_full_content1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Customize_Container_full_content1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Customize_Container_full_content1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Customize_Container_full_content1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Customize_Container_full_content1, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Customize_Container_full_content1, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Customize_Container_full_content1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Customize_Container_full_content1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Customize_Container_full_content1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Customize_Container_full_content1, 24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Customize_Panel_length_badge = lv_obj_create(ui_Customize_Container_full_content1);
    lv_obj_set_width(ui_Customize_Panel_length_badge, 76);
    lv_obj_set_height(ui_Customize_Panel_length_badge, 32);
    lv_obj_set_x(ui_Customize_Panel_length_badge, -60);
    lv_obj_set_y(ui_Customize_Panel_length_badge, 28);
    lv_obj_set_align(ui_Customize_Panel_length_badge, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Customize_Panel_length_badge, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_remove_flag(ui_Customize_Panel_length_badge, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Customize_Panel_length_badge, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Customize_Panel_length_badge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Customize_Panel_length_badge, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Customize_Panel_length_badge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Customize_Panel_length_badge, &ui_font_badge2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Customize_Panel_length_badge, 32, LV_PART_MAIN | LV_STATE_PRESSED);
    ui_object_set_themeable_style_property(ui_Customize_Panel_length_badge, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_bg_Secondary);
    ui_object_set_themeable_style_property(ui_Customize_Panel_length_badge, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_bg_Secondary);
    ui_object_set_themeable_style_property(ui_Customize_Panel_length_badge, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(ui_Customize_Panel_length_badge, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_border_width(ui_Customize_Panel_length_badge, 4, LV_PART_MAIN | LV_STATE_PRESSED);
    ui_object_set_themeable_style_property(ui_Customize_Panel_length_badge, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(ui_Customize_Panel_length_badge, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_text_font(ui_Customize_Panel_length_badge, &ui_font_badge2, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Customize_Label_coffee_ml = lv_label_create(ui_Customize_Panel_length_badge);
    lv_obj_set_width(ui_Customize_Label_coffee_ml, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Customize_Label_coffee_ml, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Customize_Label_coffee_ml, 0);
    lv_obj_set_y(ui_Customize_Label_coffee_ml, 1);
    lv_obj_set_align(ui_Customize_Label_coffee_ml, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Customize_Label_coffee_ml, "45ml");

    ui_Customize_Panel_length_badge2 = lv_obj_create(ui_Customize_Container_full_content1);
    lv_obj_set_width(ui_Customize_Panel_length_badge2, 76);
    lv_obj_set_height(ui_Customize_Panel_length_badge2, 32);
    lv_obj_set_x(ui_Customize_Panel_length_badge2, 26);
    lv_obj_set_y(ui_Customize_Panel_length_badge2, 28);
    lv_obj_set_align(ui_Customize_Panel_length_badge2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Customize_Panel_length_badge2, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_remove_flag(ui_Customize_Panel_length_badge2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Customize_Panel_length_badge2, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Customize_Panel_length_badge2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Customize_Panel_length_badge2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Customize_Panel_length_badge2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Customize_Panel_length_badge2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Customize_Panel_length_badge2, 32, LV_PART_MAIN | LV_STATE_PRESSED);
    ui_object_set_themeable_style_property(ui_Customize_Panel_length_badge2, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_bg_Secondary);
    ui_object_set_themeable_style_property(ui_Customize_Panel_length_badge2, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_bg_Secondary);
    ui_object_set_themeable_style_property(ui_Customize_Panel_length_badge2, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(ui_Customize_Panel_length_badge2, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_border_width(ui_Customize_Panel_length_badge2, 4, LV_PART_MAIN | LV_STATE_PRESSED);
    ui_object_set_themeable_style_property(ui_Customize_Panel_length_badge2, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(ui_Customize_Panel_length_badge2, LV_PART_MAIN | LV_STATE_PRESSED,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_text_font(ui_Customize_Panel_length_badge2, &ui_font_badge2, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Customize_Label_milk_ml = lv_label_create(ui_Customize_Panel_length_badge2);
    lv_obj_set_width(ui_Customize_Label_milk_ml, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Customize_Label_milk_ml, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Customize_Label_milk_ml, 0);
    lv_obj_set_y(ui_Customize_Label_milk_ml, 1);
    lv_obj_set_align(ui_Customize_Label_milk_ml, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Customize_Label_milk_ml, "250ml");

    ui_Customize_selector_coffee_selector1 = ui_Container_selector_create(ui_Customize_Container_full_content1);
    lv_obj_set_x(ui_Customize_selector_coffee_selector1, 0);
    lv_obj_set_y(ui_Customize_selector_coffee_selector1, 0);

    lv_obj_add_flag(ui_comp_get_child(ui_Customize_selector_coffee_selector1,
                                      UI_COMP_CONTAINER_SELECTOR_CONTAINER_SELECTOR__IMAGE_LEFT_CHEVRON), LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_obj_add_flag(ui_comp_get_child(ui_Customize_selector_coffee_selector1,
                                      UI_COMP_CONTAINER_SELECTOR_CONTAINER_SELECTOR__IMAGE_RIGHT_CHEVRON), LV_OBJ_FLAG_HIDDEN);    /// Flags

    ui_Customize_Container_main_parameters1 = lv_obj_create(ui_Customize_Container_full_content1);
    lv_obj_remove_style_all(ui_Customize_Container_main_parameters1);
    lv_obj_set_height(ui_Customize_Container_main_parameters1, lv_pct(100));
    lv_obj_set_flex_grow(ui_Customize_Container_main_parameters1, 3);
    lv_obj_set_align(ui_Customize_Container_main_parameters1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Customize_Container_main_parameters1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Customize_Container_main_parameters1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Customize_Container_main_parameters1,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Customize_Container_main_parameters1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Customize_Container_main_parameters1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Customize_Container_main_parameters1, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Customize_Container_main_parameters1, 44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Customize_Container_content = lv_obj_create(ui_Customize_Container_main_parameters1);
    lv_obj_remove_style_all(ui_Customize_Container_content);
    lv_obj_set_width(ui_Customize_Container_content, lv_pct(100));
    lv_obj_set_height(ui_Customize_Container_content, lv_pct(100));
    lv_obj_set_align(ui_Customize_Container_content, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Customize_Container_content, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Customize_Container_content, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Customize_Container_content, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Customize_Container_content, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Customize_Container_content, 33, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Customize_Container_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Customize_Container_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Customize_Container_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Customize_Container_content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Customize_Container_sliders = lv_obj_create(ui_Customize_Container_content);
    lv_obj_remove_style_all(ui_Customize_Container_sliders);
    lv_obj_set_height(ui_Customize_Container_sliders, lv_pct(100));
    lv_obj_set_flex_grow(ui_Customize_Container_sliders, 1);
    lv_obj_set_align(ui_Customize_Container_sliders, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Customize_Container_sliders, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Customize_Container_sliders, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Customize_Container_sliders, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Customize_Container_sliders, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Customize_Container_sliders, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Customize_Container_sliders, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Customize_Container_sliders, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Customize_parameter_parameter_slider = ui_Container_parameter_create(ui_Customize_Container_sliders);
    lv_obj_set_x(ui_Customize_parameter_parameter_slider, 0);
    lv_obj_set_y(ui_Customize_parameter_parameter_slider, 0);

    lv_slider_set_range(ui_comp_get_child(ui_Customize_parameter_parameter_slider,
                                          UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 30, 45);
    lv_slider_set_value(ui_comp_get_child(ui_Customize_parameter_parameter_slider,
                                          UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 45, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_comp_get_child(ui_Customize_parameter_parameter_slider,
                                            UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY)) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
                                                    ui_comp_get_child(ui_Customize_parameter_parameter_slider,
                                                                      UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 0, LV_ANIM_OFF);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0

    ui_Customize_parameter_parameter_slider1 = ui_Container_parameter_create(ui_Customize_Container_sliders);
    lv_obj_set_x(ui_Customize_parameter_parameter_slider1, 0);
    lv_obj_set_y(ui_Customize_parameter_parameter_slider1, 0);

    lv_slider_set_range(ui_comp_get_child(ui_Customize_parameter_parameter_slider1,
                                          UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 50, 300);
    lv_slider_set_value(ui_comp_get_child(ui_Customize_parameter_parameter_slider1,
                                          UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 250, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_comp_get_child(ui_Customize_parameter_parameter_slider1,
                                            UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY)) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
                                                    ui_comp_get_child(ui_Customize_parameter_parameter_slider1,
                                                                      UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 0, LV_ANIM_OFF);

    ui_object_set_themeable_style_property(ui_comp_get_child(ui_Customize_parameter_parameter_slider1,
                                                             UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(ui_comp_get_child(ui_Customize_parameter_parameter_slider1,
                                                             UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fg_Primary);

    ui_object_set_themeable_style_property(ui_comp_get_child(ui_Customize_parameter_parameter_slider1,
                                                             UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), LV_PART_KNOB | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMAGE_RECOLOR, _ui_theme_color_fg_Disabled);
    ui_object_set_themeable_style_property(ui_comp_get_child(ui_Customize_parameter_parameter_slider1,
                                                             UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), LV_PART_KNOB | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMAGE_RECOLOR_OPA, _ui_theme_alpha_fg_Disabled);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    lv_image_set_src(ui_comp_get_child(ui_Customize_parameter_parameter_slider1,
                                       UI_COMP_CONTAINER_PARAMETER_IMAGE_SLIDER_ICON), &ui_img_1726788397);

    ui_Customize_parameter_parameter_slider2 = ui_Container_parameter_create(ui_Customize_Container_sliders);
    lv_obj_set_x(ui_Customize_parameter_parameter_slider2, 0);
    lv_obj_set_y(ui_Customize_parameter_parameter_slider2, 0);

    lv_slider_set_range(ui_comp_get_child(ui_Customize_parameter_parameter_slider2,
                                          UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 1, 4);
    lv_slider_set_value(ui_comp_get_child(ui_Customize_parameter_parameter_slider2,
                                          UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 4, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_comp_get_child(ui_Customize_parameter_parameter_slider2,
                                            UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY)) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
                                                    ui_comp_get_child(ui_Customize_parameter_parameter_slider2,
                                                                      UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_comp_get_child(ui_Customize_parameter_parameter_slider2,
                                       UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 24);
    lv_obj_set_height(ui_comp_get_child(ui_Customize_parameter_parameter_slider2,
                                        UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 176);

    lv_obj_set_style_bg_color(ui_comp_get_child(ui_Customize_parameter_parameter_slider2,
                                                UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), lv_color_hex(0x8E989F),
                              LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_Customize_parameter_parameter_slider2,
                                              UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_comp_get_child(ui_Customize_parameter_parameter_slider2,
                                                    UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY), &ui_img_temp_body_png,
                                  LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    lv_image_set_src(ui_comp_get_child(ui_Customize_parameter_parameter_slider2,
                                       UI_COMP_CONTAINER_PARAMETER_IMAGE_SLIDER_ICON), &ui_img_temperature_png);

    ui_Customize_separator_separator4 = ui_Container_separator_create(ui_Customize_Container_main_parameters1);
    lv_obj_set_x(ui_Customize_separator_separator4, 0);
    lv_obj_set_y(ui_Customize_separator_separator4, 79);

    lv_obj_set_width(ui_comp_get_child(ui_Customize_separator_separator4, UI_COMP_CONTAINER_SEPARATOR_PANEL_TOP_PANEL), 1);
    lv_obj_set_height(ui_comp_get_child(ui_Customize_separator_separator4, UI_COMP_CONTAINER_SEPARATOR_PANEL_TOP_PANEL),
                      164);

    lv_obj_set_width(ui_comp_get_child(ui_Customize_separator_separator4, UI_COMP_CONTAINER_SEPARATOR_PANEL_BOTTOM_PANEL),
                     1);
    lv_obj_set_height(ui_comp_get_child(ui_Customize_separator_separator4, UI_COMP_CONTAINER_SEPARATOR_PANEL_BOTTOM_PANEL),
                      164);

    ui_Customize_CTA_container_CTA_container1 = ui_Container_CTA_container_create(ui_Customize_Container_full_content1);
    lv_obj_set_x(ui_Customize_CTA_container_CTA_container1, 0);
    lv_obj_set_y(ui_Customize_CTA_container_CTA_container1, 0);

    lv_obj_add_event_cb(ui_comp_get_child(ui_Customize_header_header,
                                          UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_LEFT_CONTAINER_CONTAINER_BACK_BTN),
                        ui_event_Customize_header_header_Container_header_panel_Container_left_container_Container_back_btn, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Customize_header_header,
                                          UI_COMP_CONTAINER_HEADER_CONTAINER_HEADER_PANEL_CONTAINER_RIGHT_CONTAINER_CONTAINER_SETTINGS),
                        ui_event_Customize_header_header_Container_header_panel_Container_right_container_Container_settings, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Customize_selector_coffee_selector1,
                                          UI_COMP_CONTAINER_SELECTOR_CONTAINER_SELECTOR__IMAGE_LEFT_CHEVRON),
                        ui_event_Customize_selector_coffee_selector1_Container_selector__Image_left_chevron, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Customize_selector_coffee_selector1,
                                          UI_COMP_CONTAINER_SELECTOR_CONTAINER_SELECTOR__IMAGE_RIGHT_CHEVRON),
                        ui_event_Customize_selector_coffee_selector1_Container_selector__Image_right_chevron, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Customize_parameter_parameter_slider,
                                          UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY),
                        ui_event_Customize_parameter_parameter_slider_Container_slider_Slider_slider_body, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Customize_parameter_parameter_slider1,
                                          UI_COMP_CONTAINER_PARAMETER_CONTAINER_SLIDER_SLIDER_SLIDER_BODY),
                        ui_event_Customize_parameter_parameter_slider1_Container_slider_Slider_slider_body, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_Customize_CTA_container_CTA_container1,
                                          UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL), ui_event_Customize_CTA_container_CTA_container1_Panel_circle_panel,
                        LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen_Customize, ui_event_Screen_Customize, LV_EVENT_ALL, NULL);

}

void ui_Screen_Customize_screen_destroy(void)
{
    if(ui_Screen_Customize) lv_obj_del(ui_Screen_Customize);

    // NULL screen variables
    ui_Screen_Customize = NULL;
    ui_Customize_header_header = NULL;
    ui_Customize_steps_steps = NULL;
    ui_Customize_Container_full_content1 = NULL;
    ui_Customize_Panel_length_badge = NULL;
    ui_Customize_Label_coffee_ml = NULL;
    ui_Customize_Panel_length_badge2 = NULL;
    ui_Customize_Label_milk_ml = NULL;
    ui_Customize_selector_coffee_selector1 = NULL;
    ui_Customize_Container_main_parameters1 = NULL;
    ui_Customize_Container_content = NULL;
    ui_Customize_Container_sliders = NULL;
    ui_Customize_parameter_parameter_slider = NULL;
    ui_Customize_parameter_parameter_slider1 = NULL;
    ui_Customize_parameter_parameter_slider2 = NULL;
    ui_Customize_separator_separator4 = NULL;
    ui_Customize_CTA_container_CTA_container1 = NULL;

}
