// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#ifndef UI_SCREEN_CUSTOMIZE2_H
#define UI_SCREEN_CUSTOMIZE2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_Customize2
extern void ui_Screen_Customize2_screen_init(void);
extern void ui_Screen_Customize2_screen_destroy(void);
extern void ui_event_Screen_Customize2(lv_event_t * e);
extern lv_obj_t * ui_Screen_Customize2;
extern lv_obj_t * ui_Customize2_header_header2;
extern void ui_event_Customize2_header_header2_Container_header_panel_Container_left_container_Container_back_btn(
    lv_event_t * e);
extern void ui_event_Customize2_header_header2_Container_header_panel_Container_right_container_Container_settings(
    lv_event_t * e);
extern lv_obj_t * ui_Customize2_steps_steps3;
extern lv_obj_t * ui_Customize2_Container_full_content4;
extern lv_obj_t * ui_Customize2_selector_coffee_selector4;
extern void ui_event_Customize2_selector_coffee_selector4_Container_selector__Image_left_chevron(lv_event_t * e);
extern void ui_event_Customize2_selector_coffee_selector4_Container_selector__Image_right_chevron(lv_event_t * e);
extern lv_obj_t * ui_Customize2_Container_main_parameters4;
extern lv_obj_t * ui_Customize2_Container_content1;
extern lv_obj_t * ui_Customize2_Container_sliders1;
extern lv_obj_t * ui_Customize2_parameter_parameter_slider3;
extern lv_obj_t * ui_Customize2_parameter_parameter_slider4;
extern void ui_event_Customize2_parameter_parameter_slider4_Container_slider_Slider_slider_body(lv_event_t * e);
extern lv_obj_t * ui_Customize2_Label_num;
extern lv_obj_t * ui_Customize2_separator_separator1;
extern lv_obj_t * ui_Customize2_CTA_container_CTA_container4;
extern void ui_event_Customize2_CTA_container_CTA_container4_Panel_circle_panel(lv_event_t * e);
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

