// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#include "../ui.h"

// COMPONENT Slider1

lv_obj_t * ui_Slider_Slider1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Slider_Slider1;
    cui_Slider_Slider1 = lv_slider_create(comp_parent);
    lv_slider_set_range(cui_Slider_Slider1, 0, 9);
    lv_slider_set_value(cui_Slider_Slider1, 9, LV_ANIM_OFF);
    if(lv_slider_get_mode(cui_Slider_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(cui_Slider_Slider1, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(cui_Slider_Slider1, 434);
    lv_obj_set_height(cui_Slider_Slider1, 51);
    lv_obj_set_x(cui_Slider_Slider1, -14);
    lv_obj_set_y(cui_Slider_Slider1, 61);
    lv_obj_set_align(cui_Slider_Slider1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(cui_Slider_Slider1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Slider_Slider1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Slider_Slider1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(cui_Slider_Slider1, &ui_img_disabledbean_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_tiled(cui_Slider_Slider1, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(cui_Slider_Slider1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Slider_Slider1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Slider_Slider1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(cui_Slider_Slider1, &ui_img_beans_white_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_tiled(cui_Slider_Slider1, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(cui_Slider_Slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Slider_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(cui_Slider_Slider1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(cui_Slider_Slider1,
                                                                                                      lv_obj_get_style_pad_right(cui_Slider_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_SLIDER_SLIDER1_NUM);
    children[UI_COMP_SLIDER_SLIDER1_SLIDER_SLIDER1] = cui_Slider_Slider1;
    lv_obj_add_event_cb(cui_Slider_Slider1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Slider_Slider1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Slider_Slider1_create_hook(cui_Slider_Slider1);
    return cui_Slider_Slider1;
}

