// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#include "../ui.h"

// COMPONENT separator

lv_obj_t * ui_Container_separator_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Container_separator;
    cui_Container_separator = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Container_separator);
    lv_obj_set_width(cui_Container_separator, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(cui_Container_separator, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(cui_Container_separator, 0);
    lv_obj_set_y(cui_Container_separator, 79);
    lv_obj_set_align(cui_Container_separator, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(cui_Container_separator, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_Container_separator, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_Container_separator, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Panel_top_panel;
    cui_Panel_top_panel = lv_obj_create(cui_Container_separator);
    lv_obj_set_width(cui_Panel_top_panel, 2);
    lv_obj_set_height(cui_Panel_top_panel, 164);
    lv_obj_set_x(cui_Panel_top_panel, 0);
    lv_obj_set_y(cui_Panel_top_panel, 79);
    lv_obj_set_align(cui_Panel_top_panel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(cui_Panel_top_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Panel_top_panel, lv_color_hex(0x363C41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel_top_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_Panel_top_panel, lv_color_hex(0x797F82), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(cui_Panel_top_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(cui_Panel_top_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(cui_Panel_top_panel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel_bottom_panel;
    cui_Panel_bottom_panel = lv_obj_create(cui_Container_separator);
    lv_obj_set_width(cui_Panel_bottom_panel, 2);
    lv_obj_set_height(cui_Panel_bottom_panel, 164);
    lv_obj_set_x(cui_Panel_bottom_panel, 0);
    lv_obj_set_y(cui_Panel_bottom_panel, 79);
    lv_obj_set_align(cui_Panel_bottom_panel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(cui_Panel_bottom_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Panel_bottom_panel, lv_color_hex(0x797F82), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel_bottom_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_Panel_bottom_panel, lv_color_hex(0x363C41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(cui_Panel_bottom_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(cui_Panel_bottom_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(cui_Panel_bottom_panel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINER_SEPARATOR_NUM);
    children[UI_COMP_CONTAINER_SEPARATOR_CONTAINER_SEPARATOR] = cui_Container_separator;
    children[UI_COMP_CONTAINER_SEPARATOR_PANEL_TOP_PANEL] = cui_Panel_top_panel;
    children[UI_COMP_CONTAINER_SEPARATOR_PANEL_BOTTOM_PANEL] = cui_Panel_bottom_panel;
    lv_obj_add_event_cb(cui_Container_separator, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Container_separator, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Container_separator_create_hook(cui_Container_separator);
    return cui_Container_separator;
}

