// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#include "../ui.h"

// COMPONENT Slider3

lv_obj_t * ui_Container_Slider3_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Container_Slider3;
    cui_Container_Slider3 = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Container_Slider3);
    lv_obj_set_width(cui_Container_Slider3, 494);
    lv_obj_set_height(cui_Container_Slider3, 123);
    lv_obj_set_x(cui_Container_Slider3, -18);
    lv_obj_set_y(cui_Container_Slider3, 129);
    lv_obj_set_align(cui_Container_Slider3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Container_Slider3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Slider_Slider2;
    cui_Slider_Slider2 = lv_slider_create(cui_Container_Slider3);
    lv_slider_set_range(cui_Slider_Slider2, 0, 4);
    lv_slider_set_value(cui_Slider_Slider2, 4, LV_ANIM_OFF);
    if(lv_slider_get_mode(cui_Slider_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(cui_Slider_Slider2, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(cui_Slider_Slider2, 434);
    lv_obj_set_height(cui_Slider_Slider2, 51);
    lv_obj_set_x(cui_Slider_Slider2, -12);
    lv_obj_set_y(cui_Slider_Slider2, 17);
    lv_obj_set_align(cui_Slider_Slider2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(cui_Slider_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Slider_Slider2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Slider_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(cui_Slider_Slider2, &ui_img_coffee_illustration_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(cui_Slider_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Slider_Slider2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Slider_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(cui_Slider_Slider2, &ui_img_ble_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_tiled(cui_Slider_Slider2, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(cui_Slider_Slider2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Slider_Slider2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(cui_Slider_Slider2, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(cui_Slider_Slider2,
                                                                                                      lv_obj_get_style_pad_right(cui_Slider_Slider2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_t * cui_Label_Label1;
    cui_Label_Label1 = lv_label_create(cui_Container_Slider3);
    lv_obj_set_width(cui_Label_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label_Label1, -158);
    lv_obj_set_y(cui_Label_Label1, -50);
    lv_obj_set_align(cui_Label_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label_Label1, "slider");
    lv_obj_set_style_text_color(cui_Label_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label_Label1, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINER_SLIDER3_NUM);
    children[UI_COMP_CONTAINER_SLIDER3_CONTAINER_SLIDER3] = cui_Container_Slider3;
    children[UI_COMP_CONTAINER_SLIDER3_SLIDER_SLIDER2] = cui_Slider_Slider2;
    children[UI_COMP_CONTAINER_SLIDER3_LABEL_LABEL1] = cui_Label_Label1;
    lv_obj_add_event_cb(cui_Container_Slider3, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Container_Slider3, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Container_Slider3_create_hook(cui_Container_Slider3);
    return cui_Container_Slider3;
}

