// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#ifndef UI_SCREEN_BREWING_DONE_H
#define UI_SCREEN_BREWING_DONE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_Brewing_Done
extern void ui_Screen_Brewing_Done_screen_init(void);
extern void ui_Screen_Brewing_Done_screen_destroy(void);
extern void ui_event_Screen_Brewing_Done(lv_event_t * e);
extern lv_obj_t * ui_Screen_Brewing_Done;
extern lv_obj_t * ui_Brewing_Done_header_header6;
extern lv_obj_t * ui_Brewing_Done_Label_enjoy;
extern lv_obj_t * ui_Brewing_Done_Container_full_content6;
extern lv_obj_t * ui_Brewing_Done_ready_button_ready_button;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

