// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#include "../ui.h"

lv_obj_t * ui_Screen_Splash_screen = NULL;
lv_obj_t * ui_Splash_screen_Label_caffee = NULL;
lv_obj_t * ui_Splash_screen_Label_example = NULL;
lv_obj_t * ui_Splash_screen_Label_squareline = NULL;
lv_obj_t * ui_Splash_screen_Image_shape = NULL;
lv_obj_t * ui_Splash_screen_CTA_container_CTA_container9 = NULL;
lv_obj_t * ui_Splash_screen_Image_big_espresso = NULL;
lv_obj_t * ui_Splash_screen_Image_big_ristretto = NULL;
lv_obj_t * ui_Splash_screen_Image_big_latte = NULL;
// event funtions
void ui_event_Screen_Splash_screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        home_slider_bottom_Animation(ui_Splash_screen_Image_big_latte, 0);
        home_slider_bottom_Animation(ui_Splash_screen_Image_big_ristretto, 100);
        home_slider_bottom_Animation(ui_Splash_screen_Image_big_espresso, 200);
    }
}

void ui_event_Splash_screen_CTA_container_CTA_container9_Panel_circle_panel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_Home, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen_Home_screen_init);
    }
}

// build funtions

void ui_Screen_Splash_screen_screen_init(void)
{
    ui_Screen_Splash_screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_Splash_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Screen_Splash_screen, &ui_img_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Screen_Splash_screen, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Screen_Splash_screen, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Screen_Splash_screen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Screen_Splash_screen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Splash_screen_Label_caffee = lv_label_create(ui_Screen_Splash_screen);
    lv_obj_set_width(ui_Splash_screen_Label_caffee, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Splash_screen_Label_caffee, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Splash_screen_Label_caffee, 0);
    lv_obj_set_y(ui_Splash_screen_Label_caffee, 33);
    lv_label_set_text(ui_Splash_screen_Label_caffee, "Caffee machine");
    ui_object_set_themeable_style_property(ui_Splash_screen_Label_caffee, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(ui_Splash_screen_Label_caffee, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_text_font(ui_Splash_screen_Label_caffee, &ui_font_H1_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Splash_screen_Label_example = lv_label_create(ui_Screen_Splash_screen);
    lv_obj_set_width(ui_Splash_screen_Label_example, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Splash_screen_Label_example, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Splash_screen_Label_example, 111);
    lv_obj_set_y(ui_Splash_screen_Label_example, 104);
    lv_label_set_text(ui_Splash_screen_Label_example, "Example project");
    ui_object_set_themeable_style_property(ui_Splash_screen_Label_example, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(ui_Splash_screen_Label_example, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_text_font(ui_Splash_screen_Label_example, &ui_font_H3_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Splash_screen_Label_squareline = lv_label_create(ui_Screen_Splash_screen);
    lv_obj_set_width(ui_Splash_screen_Label_squareline, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Splash_screen_Label_squareline, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Splash_screen_Label_squareline, 211);
    lv_obj_set_y(ui_Splash_screen_Label_squareline, 164);
    lv_label_set_text(ui_Splash_screen_Label_squareline, "by SquareLine Studio");
    ui_object_set_themeable_style_property(ui_Splash_screen_Label_squareline, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(ui_Splash_screen_Label_squareline, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_text_font(ui_Splash_screen_Label_squareline, &ui_font_P1_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Splash_screen_Image_shape = lv_image_create(ui_Screen_Splash_screen);
    lv_image_set_src(ui_Splash_screen_Image_shape, &ui_img_shape1_png);
    lv_obj_set_width(ui_Splash_screen_Image_shape, LV_SIZE_CONTENT);   /// 505
    lv_obj_set_height(ui_Splash_screen_Image_shape, LV_SIZE_CONTENT);    /// 623
    lv_obj_set_x(ui_Splash_screen_Image_shape, 174);
    lv_obj_set_y(ui_Splash_screen_Image_shape, -4);
    lv_obj_set_align(ui_Splash_screen_Image_shape, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Splash_screen_Image_shape, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Splash_screen_Image_shape, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Splash_screen_CTA_container_CTA_container9 = ui_Container_CTA_container_create(ui_Screen_Splash_screen);
    lv_obj_set_height(ui_Splash_screen_CTA_container_CTA_container9, lv_pct(100));
    lv_obj_set_width(ui_Splash_screen_CTA_container_CTA_container9, LV_SIZE_CONTENT);   /// 176
    lv_obj_set_flex_grow(ui_Splash_screen_CTA_container_CTA_container9, 0);
    lv_obj_set_x(ui_Splash_screen_CTA_container_CTA_container9, 1);
    lv_obj_set_y(ui_Splash_screen_CTA_container_CTA_container9, 0);
    lv_obj_set_align(ui_Splash_screen_CTA_container_CTA_container9, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_pad_left(ui_Splash_screen_CTA_container_CTA_container9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Splash_screen_CTA_container_CTA_container9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Splash_screen_CTA_container_CTA_container9, 107, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Splash_screen_CTA_container_CTA_container9, 44, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_label_set_text(ui_comp_get_child(ui_Splash_screen_CTA_container_CTA_container9,
                                        UI_COMP_CONTAINER_CTA_CONTAINER_LABEL_EXTRACT), "Get started");

    ui_Splash_screen_Image_big_espresso = lv_image_create(ui_Screen_Splash_screen);
    lv_image_set_src(ui_Splash_screen_Image_big_espresso, &ui_img_big_espresso_png);
    lv_obj_set_width(ui_Splash_screen_Image_big_espresso, LV_SIZE_CONTENT);   /// 392
    lv_obj_set_height(ui_Splash_screen_Image_big_espresso, LV_SIZE_CONTENT);    /// 221
    lv_obj_set_x(ui_Splash_screen_Image_big_espresso, -94);
    lv_obj_set_y(ui_Splash_screen_Image_big_espresso, 0);
    lv_obj_set_align(ui_Splash_screen_Image_big_espresso, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Splash_screen_Image_big_espresso, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Splash_screen_Image_big_espresso, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Splash_screen_Image_big_ristretto = lv_image_create(ui_Screen_Splash_screen);
    lv_image_set_src(ui_Splash_screen_Image_big_ristretto, &ui_img_big_ristretto_png);
    lv_obj_set_width(ui_Splash_screen_Image_big_ristretto, LV_SIZE_CONTENT);   /// 381
    lv_obj_set_height(ui_Splash_screen_Image_big_ristretto, LV_SIZE_CONTENT);    /// 233
    lv_obj_set_x(ui_Splash_screen_Image_big_ristretto, -155);
    lv_obj_set_y(ui_Splash_screen_Image_big_ristretto, 0);
    lv_obj_set_align(ui_Splash_screen_Image_big_ristretto, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Splash_screen_Image_big_ristretto, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Splash_screen_Image_big_ristretto, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Splash_screen_Image_big_latte = lv_image_create(ui_Screen_Splash_screen);
    lv_image_set_src(ui_Splash_screen_Image_big_latte, &ui_img_big_latte_png);
    lv_obj_set_width(ui_Splash_screen_Image_big_latte, LV_SIZE_CONTENT);   /// 361
    lv_obj_set_height(ui_Splash_screen_Image_big_latte, LV_SIZE_CONTENT);    /// 312
    lv_obj_set_x(ui_Splash_screen_Image_big_latte, -215);
    lv_obj_set_y(ui_Splash_screen_Image_big_latte, 0);
    lv_obj_set_align(ui_Splash_screen_Image_big_latte, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Splash_screen_Image_big_latte, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Splash_screen_Image_big_latte, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_comp_get_child(ui_Splash_screen_CTA_container_CTA_container9,
                                          UI_COMP_CONTAINER_CTA_CONTAINER_PANEL_CIRCLE_PANEL),
                        ui_event_Splash_screen_CTA_container_CTA_container9_Panel_circle_panel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen_Splash_screen, ui_event_Screen_Splash_screen, LV_EVENT_ALL, NULL);

}

void ui_Screen_Splash_screen_screen_destroy(void)
{
    if(ui_Screen_Splash_screen) lv_obj_del(ui_Screen_Splash_screen);

    // NULL screen variables
    ui_Screen_Splash_screen = NULL;
    ui_Splash_screen_Label_caffee = NULL;
    ui_Splash_screen_Label_example = NULL;
    ui_Splash_screen_Label_squareline = NULL;
    ui_Splash_screen_Image_shape = NULL;
    ui_Splash_screen_CTA_container_CTA_container9 = NULL;
    ui_Splash_screen_Image_big_espresso = NULL;
    ui_Splash_screen_Image_big_ristretto = NULL;
    ui_Splash_screen_Image_big_latte = NULL;

}
