// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#include "../ui.h"

lv_obj_t * ui_Screen_Ready = NULL;
lv_obj_t * ui_Ready_Label_enjoy = NULL;
lv_obj_t * ui_Ready_ready_button_ready_button1 = NULL;
// event funtions
void ui_event_Screen_Ready(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        enjoy_bottom_off_Animation(ui_Ready_Label_enjoy, 1500);
        enjoybtn_top_off_Animation(ui_Ready_ready_button_ready_button1, 1500);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_Screen_Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 2000, &ui_Screen_Home_screen_init);
        enjoy_bottom_on_Animation(ui_Ready_Label_enjoy, 0);
        enjoybtn_top_on_Animation(ui_Ready_ready_button_ready_button1, 0);
    }
}

// build funtions

void ui_Screen_Ready_screen_init(void)
{
    ui_Screen_Ready = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_Ready, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Screen_Ready, &ui_img_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Screen_Ready, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Screen_Ready, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Screen_Ready, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Screen_Ready, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Screen_Ready, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ready_Label_enjoy = lv_label_create(ui_Screen_Ready);
    lv_obj_set_width(ui_Ready_Label_enjoy, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ready_Label_enjoy, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ready_Label_enjoy, 0);
    lv_obj_set_y(ui_Ready_Label_enjoy, 140);
    lv_obj_set_align(ui_Ready_Label_enjoy, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ready_Label_enjoy, "Your coffee machine is \nnow ready to use!");
    ui_object_set_themeable_style_property(ui_Ready_Label_enjoy, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_fg_Primary);
    ui_object_set_themeable_style_property(ui_Ready_Label_enjoy, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_fg_Primary);
    lv_obj_set_style_text_align(ui_Ready_Label_enjoy, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ready_Label_enjoy, &ui_font_H3_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ready_ready_button_ready_button1 = ui_Panel_ready_button_create(ui_Screen_Ready);
    lv_obj_set_x(ui_Ready_ready_button_ready_button1, 0);
    lv_obj_set_y(ui_Ready_ready_button_ready_button1, -30);

    lv_obj_add_event_cb(ui_Screen_Ready, ui_event_Screen_Ready, LV_EVENT_ALL, NULL);

}

void ui_Screen_Ready_screen_destroy(void)
{
    if(ui_Screen_Ready) lv_obj_del(ui_Screen_Ready);

    // NULL screen variables
    ui_Screen_Ready = NULL;
    ui_Ready_Label_enjoy = NULL;
    ui_Ready_ready_button_ready_button1 = NULL;

}
