// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Caffee_machine

#ifndef UI_SCREEN_BREWING_H
#define UI_SCREEN_BREWING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_Brewing
extern void ui_Screen_Brewing_screen_init(void);
extern void ui_Screen_Brewing_screen_destroy(void);
extern void ui_event_Screen_Brewing(lv_event_t * e);
extern lv_obj_t * ui_Screen_Brewing;
extern lv_obj_t * ui_Brewing_header_header5;
extern lv_obj_t * ui_Brewing_Container_full_content;
extern lv_obj_t * ui_Brewing_selector_coffee_selector8;
extern lv_obj_t * ui_Brewing_Container_main_parameters;
extern lv_obj_t * ui_Brewing_Container_progress_container;
extern lv_obj_t * ui_Brewing_Panel_progressbar_bg;
extern lv_obj_t * ui_Brewing_Panel_progressbar_fg_;
extern lv_obj_t * ui_Brewing_Container_progress_labels;
extern lv_obj_t * ui_Brewing_Label_foam;
extern lv_obj_t * ui_Brewing_Label_milk;
extern lv_obj_t * ui_Brewing_Label_coffee;
extern lv_obj_t * ui_Brewing_Label_wait;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

